// Code generated by ent, DO NOT EDIT.

package groupstatusevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldGroupID, v))
}

// ConfigID applies equality check predicate on the "config_id" field. It's identical to ConfigIDEQ.
func ConfigID(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldConfigID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldEventType, v))
}

// FromStatus applies equality check predicate on the "from_status" field. It's identical to FromStatusEQ.
func FromStatus(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldFromStatus, v))
}

// ToStatus applies equality check predicate on the "to_status" field. It's identical to ToStatusEQ.
func ToStatus(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldToStatus, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// HTTPCode applies equality check predicate on the "http_code" field. It's identical to HTTPCodeEQ.
func HTTPCode(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldHTTPCode, v))
}

// SubStatus applies equality check predicate on the "sub_status" field. It's identical to SubStatusEQ.
func SubStatus(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldSubStatus, v))
}

// ErrorDetail applies equality check predicate on the "error_detail" field. It's identical to ErrorDetailEQ.
func ErrorDetail(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldErrorDetail, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldObservedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldGroupID, v))
}

// ConfigIDEQ applies the EQ predicate on the "config_id" field.
func ConfigIDEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldConfigID, v))
}

// ConfigIDNEQ applies the NEQ predicate on the "config_id" field.
func ConfigIDNEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldConfigID, v))
}

// ConfigIDIn applies the In predicate on the "config_id" field.
func ConfigIDIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldConfigID, vs...))
}

// ConfigIDNotIn applies the NotIn predicate on the "config_id" field.
func ConfigIDNotIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldConfigID, vs...))
}

// ConfigIDGT applies the GT predicate on the "config_id" field.
func ConfigIDGT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldConfigID, v))
}

// ConfigIDGTE applies the GTE predicate on the "config_id" field.
func ConfigIDGTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldConfigID, v))
}

// ConfigIDLT applies the LT predicate on the "config_id" field.
func ConfigIDLT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldConfigID, v))
}

// ConfigIDLTE applies the LTE predicate on the "config_id" field.
func ConfigIDLTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldConfigID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContainsFold(FieldEventType, v))
}

// FromStatusEQ applies the EQ predicate on the "from_status" field.
func FromStatusEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldFromStatus, v))
}

// FromStatusNEQ applies the NEQ predicate on the "from_status" field.
func FromStatusNEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldFromStatus, v))
}

// FromStatusIn applies the In predicate on the "from_status" field.
func FromStatusIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldFromStatus, vs...))
}

// FromStatusNotIn applies the NotIn predicate on the "from_status" field.
func FromStatusNotIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldFromStatus, vs...))
}

// FromStatusGT applies the GT predicate on the "from_status" field.
func FromStatusGT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldFromStatus, v))
}

// FromStatusGTE applies the GTE predicate on the "from_status" field.
func FromStatusGTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldFromStatus, v))
}

// FromStatusLT applies the LT predicate on the "from_status" field.
func FromStatusLT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldFromStatus, v))
}

// FromStatusLTE applies the LTE predicate on the "from_status" field.
func FromStatusLTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldFromStatus, v))
}

// FromStatusContains applies the Contains predicate on the "from_status" field.
func FromStatusContains(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContains(FieldFromStatus, v))
}

// FromStatusHasPrefix applies the HasPrefix predicate on the "from_status" field.
func FromStatusHasPrefix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasPrefix(FieldFromStatus, v))
}

// FromStatusHasSuffix applies the HasSuffix predicate on the "from_status" field.
func FromStatusHasSuffix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasSuffix(FieldFromStatus, v))
}

// FromStatusEqualFold applies the EqualFold predicate on the "from_status" field.
func FromStatusEqualFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEqualFold(FieldFromStatus, v))
}

// FromStatusContainsFold applies the ContainsFold predicate on the "from_status" field.
func FromStatusContainsFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContainsFold(FieldFromStatus, v))
}

// ToStatusEQ applies the EQ predicate on the "to_status" field.
func ToStatusEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldToStatus, v))
}

// ToStatusNEQ applies the NEQ predicate on the "to_status" field.
func ToStatusNEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldToStatus, v))
}

// ToStatusIn applies the In predicate on the "to_status" field.
func ToStatusIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldToStatus, vs...))
}

// ToStatusNotIn applies the NotIn predicate on the "to_status" field.
func ToStatusNotIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldToStatus, vs...))
}

// ToStatusGT applies the GT predicate on the "to_status" field.
func ToStatusGT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldToStatus, v))
}

// ToStatusGTE applies the GTE predicate on the "to_status" field.
func ToStatusGTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldToStatus, v))
}

// ToStatusLT applies the LT predicate on the "to_status" field.
func ToStatusLT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldToStatus, v))
}

// ToStatusLTE applies the LTE predicate on the "to_status" field.
func ToStatusLTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldToStatus, v))
}

// ToStatusContains applies the Contains predicate on the "to_status" field.
func ToStatusContains(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContains(FieldToStatus, v))
}

// ToStatusHasPrefix applies the HasPrefix predicate on the "to_status" field.
func ToStatusHasPrefix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasPrefix(FieldToStatus, v))
}

// ToStatusHasSuffix applies the HasSuffix predicate on the "to_status" field.
func ToStatusHasSuffix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasSuffix(FieldToStatus, v))
}

// ToStatusEqualFold applies the EqualFold predicate on the "to_status" field.
func ToStatusEqualFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEqualFold(FieldToStatus, v))
}

// ToStatusContainsFold applies the ContainsFold predicate on the "to_status" field.
func ToStatusContainsFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContainsFold(FieldToStatus, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotNull(FieldLatencyMs))
}

// HTTPCodeEQ applies the EQ predicate on the "http_code" field.
func HTTPCodeEQ(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldHTTPCode, v))
}

// HTTPCodeNEQ applies the NEQ predicate on the "http_code" field.
func HTTPCodeNEQ(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldHTTPCode, v))
}

// HTTPCodeIn applies the In predicate on the "http_code" field.
func HTTPCodeIn(vs ...int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldHTTPCode, vs...))
}

// HTTPCodeNotIn applies the NotIn predicate on the "http_code" field.
func HTTPCodeNotIn(vs ...int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldHTTPCode, vs...))
}

// HTTPCodeGT applies the GT predicate on the "http_code" field.
func HTTPCodeGT(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldHTTPCode, v))
}

// HTTPCodeGTE applies the GTE predicate on the "http_code" field.
func HTTPCodeGTE(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldHTTPCode, v))
}

// HTTPCodeLT applies the LT predicate on the "http_code" field.
func HTTPCodeLT(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldHTTPCode, v))
}

// HTTPCodeLTE applies the LTE predicate on the "http_code" field.
func HTTPCodeLTE(v int) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldHTTPCode, v))
}

// HTTPCodeIsNil applies the IsNil predicate on the "http_code" field.
func HTTPCodeIsNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIsNull(FieldHTTPCode))
}

// HTTPCodeNotNil applies the NotNil predicate on the "http_code" field.
func HTTPCodeNotNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotNull(FieldHTTPCode))
}

// SubStatusEQ applies the EQ predicate on the "sub_status" field.
func SubStatusEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldSubStatus, v))
}

// SubStatusNEQ applies the NEQ predicate on the "sub_status" field.
func SubStatusNEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldSubStatus, v))
}

// SubStatusIn applies the In predicate on the "sub_status" field.
func SubStatusIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldSubStatus, vs...))
}

// SubStatusNotIn applies the NotIn predicate on the "sub_status" field.
func SubStatusNotIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldSubStatus, vs...))
}

// SubStatusGT applies the GT predicate on the "sub_status" field.
func SubStatusGT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldSubStatus, v))
}

// SubStatusGTE applies the GTE predicate on the "sub_status" field.
func SubStatusGTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldSubStatus, v))
}

// SubStatusLT applies the LT predicate on the "sub_status" field.
func SubStatusLT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldSubStatus, v))
}

// SubStatusLTE applies the LTE predicate on the "sub_status" field.
func SubStatusLTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldSubStatus, v))
}

// SubStatusContains applies the Contains predicate on the "sub_status" field.
func SubStatusContains(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContains(FieldSubStatus, v))
}

// SubStatusHasPrefix applies the HasPrefix predicate on the "sub_status" field.
func SubStatusHasPrefix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasPrefix(FieldSubStatus, v))
}

// SubStatusHasSuffix applies the HasSuffix predicate on the "sub_status" field.
func SubStatusHasSuffix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasSuffix(FieldSubStatus, v))
}

// SubStatusEqualFold applies the EqualFold predicate on the "sub_status" field.
func SubStatusEqualFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEqualFold(FieldSubStatus, v))
}

// SubStatusContainsFold applies the ContainsFold predicate on the "sub_status" field.
func SubStatusContainsFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContainsFold(FieldSubStatus, v))
}

// ErrorDetailEQ applies the EQ predicate on the "error_detail" field.
func ErrorDetailEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldErrorDetail, v))
}

// ErrorDetailNEQ applies the NEQ predicate on the "error_detail" field.
func ErrorDetailNEQ(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldErrorDetail, v))
}

// ErrorDetailIn applies the In predicate on the "error_detail" field.
func ErrorDetailIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldErrorDetail, vs...))
}

// ErrorDetailNotIn applies the NotIn predicate on the "error_detail" field.
func ErrorDetailNotIn(vs ...string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldErrorDetail, vs...))
}

// ErrorDetailGT applies the GT predicate on the "error_detail" field.
func ErrorDetailGT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldErrorDetail, v))
}

// ErrorDetailGTE applies the GTE predicate on the "error_detail" field.
func ErrorDetailGTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldErrorDetail, v))
}

// ErrorDetailLT applies the LT predicate on the "error_detail" field.
func ErrorDetailLT(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldErrorDetail, v))
}

// ErrorDetailLTE applies the LTE predicate on the "error_detail" field.
func ErrorDetailLTE(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldErrorDetail, v))
}

// ErrorDetailContains applies the Contains predicate on the "error_detail" field.
func ErrorDetailContains(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContains(FieldErrorDetail, v))
}

// ErrorDetailHasPrefix applies the HasPrefix predicate on the "error_detail" field.
func ErrorDetailHasPrefix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasPrefix(FieldErrorDetail, v))
}

// ErrorDetailHasSuffix applies the HasSuffix predicate on the "error_detail" field.
func ErrorDetailHasSuffix(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldHasSuffix(FieldErrorDetail, v))
}

// ErrorDetailIsNil applies the IsNil predicate on the "error_detail" field.
func ErrorDetailIsNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIsNull(FieldErrorDetail))
}

// ErrorDetailNotNil applies the NotNil predicate on the "error_detail" field.
func ErrorDetailNotNil() predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotNull(FieldErrorDetail))
}

// ErrorDetailEqualFold applies the EqualFold predicate on the "error_detail" field.
func ErrorDetailEqualFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEqualFold(FieldErrorDetail, v))
}

// ErrorDetailContainsFold applies the ContainsFold predicate on the "error_detail" field.
func ErrorDetailContainsFold(v string) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldContainsFold(FieldErrorDetail, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldObservedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupStatusEvent) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupStatusEvent) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupStatusEvent) predicate.GroupStatusEvent {
	return predicate.GroupStatusEvent(sql.NotPredicates(p))
}
