// Code generated by ent, DO NOT EDIT.

package userreferral

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldID, id))
}

// ReferrerID applies equality check predicate on the "referrer_id" field. It's identical to ReferrerIDEQ.
func ReferrerID(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerID, v))
}

// RefereeID applies equality check predicate on the "referee_id" field. It's identical to RefereeIDEQ.
func RefereeID(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldStatus, v))
}

// ReferrerBalanceReward applies equality check predicate on the "referrer_balance_reward" field. It's identical to ReferrerBalanceRewardEQ.
func ReferrerBalanceReward(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerBalanceReward, v))
}

// ReferrerGroupID applies equality check predicate on the "referrer_group_id" field. It's identical to ReferrerGroupIDEQ.
func ReferrerGroupID(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerGroupID, v))
}

// ReferrerSubscriptionDays applies equality check predicate on the "referrer_subscription_days" field. It's identical to ReferrerSubscriptionDaysEQ.
func ReferrerSubscriptionDays(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerSubscriptionDays, v))
}

// ReferrerRewardedAt applies equality check predicate on the "referrer_rewarded_at" field. It's identical to ReferrerRewardedAtEQ.
func ReferrerRewardedAt(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerRewardedAt, v))
}

// RefereeBalanceReward applies equality check predicate on the "referee_balance_reward" field. It's identical to RefereeBalanceRewardEQ.
func RefereeBalanceReward(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeBalanceReward, v))
}

// RefereeGroupID applies equality check predicate on the "referee_group_id" field. It's identical to RefereeGroupIDEQ.
func RefereeGroupID(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeGroupID, v))
}

// RefereeSubscriptionDays applies equality check predicate on the "referee_subscription_days" field. It's identical to RefereeSubscriptionDaysEQ.
func RefereeSubscriptionDays(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeSubscriptionDays, v))
}

// RefereeRewardedAt applies equality check predicate on the "referee_rewarded_at" field. It's identical to RefereeRewardedAtEQ.
func RefereeRewardedAt(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeRewardedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReferrerIDEQ applies the EQ predicate on the "referrer_id" field.
func ReferrerIDEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerID, v))
}

// ReferrerIDNEQ applies the NEQ predicate on the "referrer_id" field.
func ReferrerIDNEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldReferrerID, v))
}

// ReferrerIDIn applies the In predicate on the "referrer_id" field.
func ReferrerIDIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldReferrerID, vs...))
}

// ReferrerIDNotIn applies the NotIn predicate on the "referrer_id" field.
func ReferrerIDNotIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldReferrerID, vs...))
}

// RefereeIDEQ applies the EQ predicate on the "referee_id" field.
func RefereeIDEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeID, v))
}

// RefereeIDNEQ applies the NEQ predicate on the "referee_id" field.
func RefereeIDNEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldRefereeID, v))
}

// RefereeIDIn applies the In predicate on the "referee_id" field.
func RefereeIDIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldRefereeID, vs...))
}

// RefereeIDNotIn applies the NotIn predicate on the "referee_id" field.
func RefereeIDNotIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldRefereeID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldContainsFold(FieldStatus, v))
}

// ReferrerBalanceRewardEQ applies the EQ predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardEQ(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerBalanceReward, v))
}

// ReferrerBalanceRewardNEQ applies the NEQ predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardNEQ(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldReferrerBalanceReward, v))
}

// ReferrerBalanceRewardIn applies the In predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardIn(vs ...float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldReferrerBalanceReward, vs...))
}

// ReferrerBalanceRewardNotIn applies the NotIn predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardNotIn(vs ...float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldReferrerBalanceReward, vs...))
}

// ReferrerBalanceRewardGT applies the GT predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardGT(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldReferrerBalanceReward, v))
}

// ReferrerBalanceRewardGTE applies the GTE predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardGTE(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldReferrerBalanceReward, v))
}

// ReferrerBalanceRewardLT applies the LT predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardLT(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldReferrerBalanceReward, v))
}

// ReferrerBalanceRewardLTE applies the LTE predicate on the "referrer_balance_reward" field.
func ReferrerBalanceRewardLTE(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldReferrerBalanceReward, v))
}

// ReferrerGroupIDEQ applies the EQ predicate on the "referrer_group_id" field.
func ReferrerGroupIDEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerGroupID, v))
}

// ReferrerGroupIDNEQ applies the NEQ predicate on the "referrer_group_id" field.
func ReferrerGroupIDNEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldReferrerGroupID, v))
}

// ReferrerGroupIDIn applies the In predicate on the "referrer_group_id" field.
func ReferrerGroupIDIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldReferrerGroupID, vs...))
}

// ReferrerGroupIDNotIn applies the NotIn predicate on the "referrer_group_id" field.
func ReferrerGroupIDNotIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldReferrerGroupID, vs...))
}

// ReferrerGroupIDGT applies the GT predicate on the "referrer_group_id" field.
func ReferrerGroupIDGT(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldReferrerGroupID, v))
}

// ReferrerGroupIDGTE applies the GTE predicate on the "referrer_group_id" field.
func ReferrerGroupIDGTE(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldReferrerGroupID, v))
}

// ReferrerGroupIDLT applies the LT predicate on the "referrer_group_id" field.
func ReferrerGroupIDLT(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldReferrerGroupID, v))
}

// ReferrerGroupIDLTE applies the LTE predicate on the "referrer_group_id" field.
func ReferrerGroupIDLTE(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldReferrerGroupID, v))
}

// ReferrerGroupIDIsNil applies the IsNil predicate on the "referrer_group_id" field.
func ReferrerGroupIDIsNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIsNull(FieldReferrerGroupID))
}

// ReferrerGroupIDNotNil applies the NotNil predicate on the "referrer_group_id" field.
func ReferrerGroupIDNotNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotNull(FieldReferrerGroupID))
}

// ReferrerSubscriptionDaysEQ applies the EQ predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysEQ(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerSubscriptionDays, v))
}

// ReferrerSubscriptionDaysNEQ applies the NEQ predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysNEQ(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldReferrerSubscriptionDays, v))
}

// ReferrerSubscriptionDaysIn applies the In predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysIn(vs ...int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldReferrerSubscriptionDays, vs...))
}

// ReferrerSubscriptionDaysNotIn applies the NotIn predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysNotIn(vs ...int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldReferrerSubscriptionDays, vs...))
}

// ReferrerSubscriptionDaysGT applies the GT predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysGT(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldReferrerSubscriptionDays, v))
}

// ReferrerSubscriptionDaysGTE applies the GTE predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysGTE(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldReferrerSubscriptionDays, v))
}

// ReferrerSubscriptionDaysLT applies the LT predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysLT(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldReferrerSubscriptionDays, v))
}

// ReferrerSubscriptionDaysLTE applies the LTE predicate on the "referrer_subscription_days" field.
func ReferrerSubscriptionDaysLTE(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldReferrerSubscriptionDays, v))
}

// ReferrerRewardedAtEQ applies the EQ predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtNEQ applies the NEQ predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtNEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtIn applies the In predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldReferrerRewardedAt, vs...))
}

// ReferrerRewardedAtNotIn applies the NotIn predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtNotIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldReferrerRewardedAt, vs...))
}

// ReferrerRewardedAtGT applies the GT predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtGT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtGTE applies the GTE predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtGTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtLT applies the LT predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtLT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtLTE applies the LTE predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtLTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldReferrerRewardedAt, v))
}

// ReferrerRewardedAtIsNil applies the IsNil predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtIsNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIsNull(FieldReferrerRewardedAt))
}

// ReferrerRewardedAtNotNil applies the NotNil predicate on the "referrer_rewarded_at" field.
func ReferrerRewardedAtNotNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotNull(FieldReferrerRewardedAt))
}

// RefereeBalanceRewardEQ applies the EQ predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardEQ(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeBalanceReward, v))
}

// RefereeBalanceRewardNEQ applies the NEQ predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardNEQ(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldRefereeBalanceReward, v))
}

// RefereeBalanceRewardIn applies the In predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardIn(vs ...float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldRefereeBalanceReward, vs...))
}

// RefereeBalanceRewardNotIn applies the NotIn predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardNotIn(vs ...float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldRefereeBalanceReward, vs...))
}

// RefereeBalanceRewardGT applies the GT predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardGT(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldRefereeBalanceReward, v))
}

// RefereeBalanceRewardGTE applies the GTE predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardGTE(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldRefereeBalanceReward, v))
}

// RefereeBalanceRewardLT applies the LT predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardLT(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldRefereeBalanceReward, v))
}

// RefereeBalanceRewardLTE applies the LTE predicate on the "referee_balance_reward" field.
func RefereeBalanceRewardLTE(v float64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldRefereeBalanceReward, v))
}

// RefereeGroupIDEQ applies the EQ predicate on the "referee_group_id" field.
func RefereeGroupIDEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeGroupID, v))
}

// RefereeGroupIDNEQ applies the NEQ predicate on the "referee_group_id" field.
func RefereeGroupIDNEQ(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldRefereeGroupID, v))
}

// RefereeGroupIDIn applies the In predicate on the "referee_group_id" field.
func RefereeGroupIDIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldRefereeGroupID, vs...))
}

// RefereeGroupIDNotIn applies the NotIn predicate on the "referee_group_id" field.
func RefereeGroupIDNotIn(vs ...int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldRefereeGroupID, vs...))
}

// RefereeGroupIDGT applies the GT predicate on the "referee_group_id" field.
func RefereeGroupIDGT(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldRefereeGroupID, v))
}

// RefereeGroupIDGTE applies the GTE predicate on the "referee_group_id" field.
func RefereeGroupIDGTE(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldRefereeGroupID, v))
}

// RefereeGroupIDLT applies the LT predicate on the "referee_group_id" field.
func RefereeGroupIDLT(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldRefereeGroupID, v))
}

// RefereeGroupIDLTE applies the LTE predicate on the "referee_group_id" field.
func RefereeGroupIDLTE(v int64) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldRefereeGroupID, v))
}

// RefereeGroupIDIsNil applies the IsNil predicate on the "referee_group_id" field.
func RefereeGroupIDIsNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIsNull(FieldRefereeGroupID))
}

// RefereeGroupIDNotNil applies the NotNil predicate on the "referee_group_id" field.
func RefereeGroupIDNotNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotNull(FieldRefereeGroupID))
}

// RefereeSubscriptionDaysEQ applies the EQ predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysEQ(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeSubscriptionDays, v))
}

// RefereeSubscriptionDaysNEQ applies the NEQ predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysNEQ(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldRefereeSubscriptionDays, v))
}

// RefereeSubscriptionDaysIn applies the In predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysIn(vs ...int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldRefereeSubscriptionDays, vs...))
}

// RefereeSubscriptionDaysNotIn applies the NotIn predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysNotIn(vs ...int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldRefereeSubscriptionDays, vs...))
}

// RefereeSubscriptionDaysGT applies the GT predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysGT(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldRefereeSubscriptionDays, v))
}

// RefereeSubscriptionDaysGTE applies the GTE predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysGTE(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldRefereeSubscriptionDays, v))
}

// RefereeSubscriptionDaysLT applies the LT predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysLT(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldRefereeSubscriptionDays, v))
}

// RefereeSubscriptionDaysLTE applies the LTE predicate on the "referee_subscription_days" field.
func RefereeSubscriptionDaysLTE(v int) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldRefereeSubscriptionDays, v))
}

// RefereeRewardedAtEQ applies the EQ predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtNEQ applies the NEQ predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtNEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtIn applies the In predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldRefereeRewardedAt, vs...))
}

// RefereeRewardedAtNotIn applies the NotIn predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtNotIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldRefereeRewardedAt, vs...))
}

// RefereeRewardedAtGT applies the GT predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtGT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtGTE applies the GTE predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtGTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtLT applies the LT predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtLT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtLTE applies the LTE predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtLTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldRefereeRewardedAt, v))
}

// RefereeRewardedAtIsNil applies the IsNil predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtIsNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIsNull(FieldRefereeRewardedAt))
}

// RefereeRewardedAtNotNil applies the NotNil predicate on the "referee_rewarded_at" field.
func RefereeRewardedAtNotNil() predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotNull(FieldRefereeRewardedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserReferral {
	return predicate.UserReferral(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasReferrer applies the HasEdge predicate on the "referrer" edge.
func HasReferrer() predicate.UserReferral {
	return predicate.UserReferral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferrerWith applies the HasEdge predicate on the "referrer" edge with a given conditions (other predicates).
func HasReferrerWith(preds ...predicate.User) predicate.UserReferral {
	return predicate.UserReferral(func(s *sql.Selector) {
		step := newReferrerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferee applies the HasEdge predicate on the "referee" edge.
func HasReferee() predicate.UserReferral {
	return predicate.UserReferral(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RefereeTable, RefereeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRefereeWith applies the HasEdge predicate on the "referee" edge with a given conditions (other predicates).
func HasRefereeWith(preds ...predicate.User) predicate.UserReferral {
	return predicate.UserReferral(func(s *sql.Selector) {
		step := newRefereeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserReferral) predicate.UserReferral {
	return predicate.UserReferral(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserReferral) predicate.UserReferral {
	return predicate.UserReferral(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserReferral) predicate.UserReferral {
	return predicate.UserReferral(sql.NotPredicates(p))
}
