// Code generated by ent, DO NOT EDIT.

package supportticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the supportticket type in the database.
	Label = "support_ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUserUnread holds the string denoting the user_unread field in the database.
	FieldUserUnread = "user_unread"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldClosedByUserID holds the string denoting the closed_by_user_id field in the database.
	FieldClosedByUserID = "closed_by_user_id"
	// FieldClosedByRole holds the string denoting the closed_by_role field in the database.
	FieldClosedByRole = "closed_by_role"
	// Table holds the table name of the supportticket in the database.
	Table = "support_tickets"
)

// Columns holds all SQL columns for supportticket fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldUserEmail,
	FieldTitle,
	FieldCategory,
	FieldStatus,
	FieldUserUnread,
	FieldMessageCount,
	FieldLastMessageAt,
	FieldClosedAt,
	FieldClosedByUserID,
	FieldClosedByRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultUserEmail holds the default value on creation for the "user_email" field.
	DefaultUserEmail string
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultUserUnread holds the default value on creation for the "user_unread" field.
	DefaultUserUnread bool
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int
	// DefaultLastMessageAt holds the default value on creation for the "last_message_at" field.
	DefaultLastMessageAt func() time.Time
	// DefaultClosedByRole holds the default value on creation for the "closed_by_role" field.
	DefaultClosedByRole string
	// ClosedByRoleValidator is a validator for the "closed_by_role" field. It is called by the builders before save.
	ClosedByRoleValidator func(string) error
)

// OrderOption defines the ordering options for the SupportTicket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUserUnread orders the results by the user_unread field.
func ByUserUnread(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserUnread, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByClosedByUserID orders the results by the closed_by_user_id field.
func ByClosedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedByUserID, opts...).ToFunc()
}

// ByClosedByRole orders the results by the closed_by_role field.
func ByClosedByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedByRole, opts...).ToFunc()
}
