// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminapprovalrequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdminApprovalRequestUpdate is the builder for updating AdminApprovalRequest entities.
type AdminApprovalRequestUpdate struct {
	config
	hooks    []Hook
	mutation *AdminApprovalRequestMutation
}

// Where appends a list predicates to the AdminApprovalRequestUpdate builder.
func (_u *AdminApprovalRequestUpdate) Where(ps ...predicate.AdminApprovalRequest) *AdminApprovalRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminApprovalRequestUpdate) SetUpdatedAt(v time.Time) *AdminApprovalRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AdminApprovalRequestUpdate) SetStatus(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableStatus(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AdminApprovalRequestUpdate) SetAction(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableAction(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdminApprovalRequestUpdate) SetMethod(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableMethod(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRouteTemplate sets the "route_template" field.
func (_u *AdminApprovalRequestUpdate) SetRouteTemplate(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRouteTemplate(v)
	return _u
}

// SetNillableRouteTemplate sets the "route_template" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRouteTemplate(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRouteTemplate(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *AdminApprovalRequestUpdate) SetRequestPath(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestPath(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetRequestQuery sets the "request_query" field.
func (_u *AdminApprovalRequestUpdate) SetRequestQuery(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestQuery(v)
	return _u
}

// SetNillableRequestQuery sets the "request_query" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestQuery(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestQuery(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *AdminApprovalRequestUpdate) SetContentType(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableContentType(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetRequestBodyEnc sets the "request_body_enc" field.
func (_u *AdminApprovalRequestUpdate) SetRequestBodyEnc(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestBodyEnc(v)
	return _u
}

// SetNillableRequestBodyEnc sets the "request_body_enc" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestBodyEnc(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestBodyEnc(*v)
	}
	return _u
}

// SetRequestBodyRedacted sets the "request_body_redacted" field.
func (_u *AdminApprovalRequestUpdate) SetRequestBodyRedacted(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestBodyRedacted(v)
	return _u
}

// SetNillableRequestBodyRedacted sets the "request_body_redacted" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestBodyRedacted(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestBodyRedacted(*v)
	}
	return _u
}

// SetRequestBodySha256 sets the "request_body_sha256" field.
func (_u *AdminApprovalRequestUpdate) SetRequestBodySha256(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestBodySha256(v)
	return _u
}

// SetNillableRequestBodySha256 sets the "request_body_sha256" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestBodySha256(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestBodySha256(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AdminApprovalRequestUpdate) SetTargetType(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableTargetType(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AdminApprovalRequestUpdate) SetTargetID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableTargetID(v *int64) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *AdminApprovalRequestUpdate) AddTargetID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AdminApprovalRequestUpdate) ClearTargetID() *AdminApprovalRequestUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetSummary sets the "target_summary" field.
func (_u *AdminApprovalRequestUpdate) SetTargetSummary(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetTargetSummary(v)
	return _u
}

// SetNillableTargetSummary sets the "target_summary" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableTargetSummary(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetTargetSummary(*v)
	}
	return _u
}

// SetRequesterUserID sets the "requester_user_id" field.
func (_u *AdminApprovalRequestUpdate) SetRequesterUserID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.ResetRequesterUserID()
	_u.mutation.SetRequesterUserID(v)
	return _u
}

// SetNillableRequesterUserID sets the "requester_user_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequesterUserID(v *int64) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequesterUserID(*v)
	}
	return _u
}

// AddRequesterUserID adds value to the "requester_user_id" field.
func (_u *AdminApprovalRequestUpdate) AddRequesterUserID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.AddRequesterUserID(v)
	return _u
}

// SetRequesterEmail sets the "requester_email" field.
func (_u *AdminApprovalRequestUpdate) SetRequesterEmail(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequesterEmail(v)
	return _u
}

// SetNillableRequesterEmail sets the "requester_email" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequesterEmail(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequesterEmail(*v)
	}
	return _u
}

// SetRequesterIP sets the "requester_ip" field.
func (_u *AdminApprovalRequestUpdate) SetRequesterIP(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequesterIP(v)
	return _u
}

// SetNillableRequesterIP sets the "requester_ip" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequesterIP(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequesterIP(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AdminApprovalRequestUpdate) SetRequestID(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableRequestID(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDecidedByUserID sets the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdate) SetDecidedByUserID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.ResetDecidedByUserID()
	_u.mutation.SetDecidedByUserID(v)
	return _u
}

// SetNillableDecidedByUserID sets the "decided_by_user_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableDecidedByUserID(v *int64) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetDecidedByUserID(*v)
	}
	return _u
}

// AddDecidedByUserID adds value to the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdate) AddDecidedByUserID(v int64) *AdminApprovalRequestUpdate {
	_u.mutation.AddDecidedByUserID(v)
	return _u
}

// ClearDecidedByUserID clears the value of the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdate) ClearDecidedByUserID() *AdminApprovalRequestUpdate {
	_u.mutation.ClearDecidedByUserID()
	return _u
}

// SetDecidedByEmail sets the "decided_by_email" field.
func (_u *AdminApprovalRequestUpdate) SetDecidedByEmail(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetDecidedByEmail(v)
	return _u
}

// SetNillableDecidedByEmail sets the "decided_by_email" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableDecidedByEmail(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetDecidedByEmail(*v)
	}
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *AdminApprovalRequestUpdate) SetDecidedAt(v time.Time) *AdminApprovalRequestUpdate {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableDecidedAt(v *time.Time) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *AdminApprovalRequestUpdate) ClearDecidedAt() *AdminApprovalRequestUpdate {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetDecisionReason sets the "decision_reason" field.
func (_u *AdminApprovalRequestUpdate) SetDecisionReason(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetDecisionReason(v)
	return _u
}

// SetNillableDecisionReason sets the "decision_reason" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableDecisionReason(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetDecisionReason(*v)
	}
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *AdminApprovalRequestUpdate) SetExecutedAt(v time.Time) *AdminApprovalRequestUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableExecutedAt(v *time.Time) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *AdminApprovalRequestUpdate) ClearExecutedAt() *AdminApprovalRequestUpdate {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetResultStatusCode sets the "result_status_code" field.
func (_u *AdminApprovalRequestUpdate) SetResultStatusCode(v int) *AdminApprovalRequestUpdate {
	_u.mutation.ResetResultStatusCode()
	_u.mutation.SetResultStatusCode(v)
	return _u
}

// SetNillableResultStatusCode sets the "result_status_code" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableResultStatusCode(v *int) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetResultStatusCode(*v)
	}
	return _u
}

// AddResultStatusCode adds value to the "result_status_code" field.
func (_u *AdminApprovalRequestUpdate) AddResultStatusCode(v int) *AdminApprovalRequestUpdate {
	_u.mutation.AddResultStatusCode(v)
	return _u
}

// ClearResultStatusCode clears the value of the "result_status_code" field.
func (_u *AdminApprovalRequestUpdate) ClearResultStatusCode() *AdminApprovalRequestUpdate {
	_u.mutation.ClearResultStatusCode()
	return _u
}

// SetResultBody sets the "result_body" field.
func (_u *AdminApprovalRequestUpdate) SetResultBody(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetResultBody(v)
	return _u
}

// SetNillableResultBody sets the "result_body" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableResultBody(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetResultBody(*v)
	}
	return _u
}

// SetResultError sets the "result_error" field.
func (_u *AdminApprovalRequestUpdate) SetResultError(v string) *AdminApprovalRequestUpdate {
	_u.mutation.SetResultError(v)
	return _u
}

// SetNillableResultError sets the "result_error" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableResultError(v *string) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetResultError(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *AdminApprovalRequestUpdate) SetNotifiedAt(v time.Time) *AdminApprovalRequestUpdate {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableNotifiedAt(v *time.Time) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *AdminApprovalRequestUpdate) ClearNotifiedAt() *AdminApprovalRequestUpdate {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminApprovalRequestUpdate) SetExpiresAt(v time.Time) *AdminApprovalRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdate) SetNillableExpiresAt(v *time.Time) *AdminApprovalRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AdminApprovalRequestMutation object of the builder.
func (_u *AdminApprovalRequestUpdate) Mutation() *AdminApprovalRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminApprovalRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminApprovalRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminApprovalRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminApprovalRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminApprovalRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminapprovalrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminApprovalRequestUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := adminapprovalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := adminapprovalrequest.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := adminapprovalrequest.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteTemplate(); ok {
		if err := adminapprovalrequest.RouteTemplateValidator(v); err != nil {
			return &ValidationError{Name: "route_template", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.route_template": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := adminapprovalrequest.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := adminapprovalrequest.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodySha256(); ok {
		if err := adminapprovalrequest.RequestBodySha256Validator(v); err != nil {
			return &ValidationError{Name: "request_body_sha256", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := adminapprovalrequest.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetSummary(); ok {
		if err := adminapprovalrequest.TargetSummaryValidator(v); err != nil {
			return &ValidationError{Name: "target_summary", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.target_summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequesterEmail(); ok {
		if err := adminapprovalrequest.RequesterEmailValidator(v); err != nil {
			return &ValidationError{Name: "requester_email", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.requester_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequesterIP(); ok {
		if err := adminapprovalrequest.RequesterIPValidator(v); err != nil {
			return &ValidationError{Name: "requester_ip", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.requester_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adminapprovalrequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecidedByEmail(); ok {
		if err := adminapprovalrequest.DecidedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "decided_by_email", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.decided_by_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultError(); ok {
		if err := adminapprovalrequest.ResultErrorValidator(v); err != nil {
			return &ValidationError{Name: "result_error", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.result_error": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminApprovalRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminapprovalrequest.Table, adminapprovalrequest.Columns, sqlgraph.NewFieldSpec(adminapprovalrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(adminapprovalrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(adminapprovalrequest.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adminapprovalrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteTemplate(); ok {
		_spec.SetField(adminapprovalrequest.FieldRouteTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestQuery(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(adminapprovalrequest.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyEnc(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodyEnc, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyRedacted(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodyRedacted, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodySha256(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(adminapprovalrequest.FieldTargetID, field.TypeInt64, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(adminapprovalrequest.FieldTargetID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TargetSummary(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterUserID(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequesterUserID(); ok {
		_spec.AddField(adminapprovalrequest.FieldRequesterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequesterEmail(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterIP(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedByUserID(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDecidedByUserID(); ok {
		_spec.AddField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.DecidedByUserIDCleared() {
		_spec.ClearField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DecidedByEmail(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedByEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldDecidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionReason(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecisionReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldExecutedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultStatusCode(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultStatusCode(); ok {
		_spec.AddField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt, value)
	}
	if _u.mutation.ResultStatusCodeCleared() {
		_spec.ClearField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResultBody(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultError(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultError, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminapprovalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminApprovalRequestUpdateOne is the builder for updating a single AdminApprovalRequest entity.
type AdminApprovalRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminApprovalRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminApprovalRequestUpdateOne) SetUpdatedAt(v time.Time) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AdminApprovalRequestUpdateOne) SetStatus(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableStatus(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AdminApprovalRequestUpdateOne) SetAction(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableAction(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdminApprovalRequestUpdateOne) SetMethod(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableMethod(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRouteTemplate sets the "route_template" field.
func (_u *AdminApprovalRequestUpdateOne) SetRouteTemplate(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRouteTemplate(v)
	return _u
}

// SetNillableRouteTemplate sets the "route_template" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRouteTemplate(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRouteTemplate(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestPath(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestPath(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetRequestQuery sets the "request_query" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestQuery(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestQuery(v)
	return _u
}

// SetNillableRequestQuery sets the "request_query" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestQuery(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestQuery(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *AdminApprovalRequestUpdateOne) SetContentType(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableContentType(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetRequestBodyEnc sets the "request_body_enc" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestBodyEnc(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestBodyEnc(v)
	return _u
}

// SetNillableRequestBodyEnc sets the "request_body_enc" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestBodyEnc(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestBodyEnc(*v)
	}
	return _u
}

// SetRequestBodyRedacted sets the "request_body_redacted" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestBodyRedacted(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestBodyRedacted(v)
	return _u
}

// SetNillableRequestBodyRedacted sets the "request_body_redacted" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestBodyRedacted(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestBodyRedacted(*v)
	}
	return _u
}

// SetRequestBodySha256 sets the "request_body_sha256" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestBodySha256(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestBodySha256(v)
	return _u
}

// SetNillableRequestBodySha256 sets the "request_body_sha256" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestBodySha256(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestBodySha256(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AdminApprovalRequestUpdateOne) SetTargetType(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableTargetType(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AdminApprovalRequestUpdateOne) SetTargetID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableTargetID(v *int64) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *AdminApprovalRequestUpdateOne) AddTargetID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AdminApprovalRequestUpdateOne) ClearTargetID() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetSummary sets the "target_summary" field.
func (_u *AdminApprovalRequestUpdateOne) SetTargetSummary(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetTargetSummary(v)
	return _u
}

// SetNillableTargetSummary sets the "target_summary" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableTargetSummary(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetTargetSummary(*v)
	}
	return _u
}

// SetRequesterUserID sets the "requester_user_id" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequesterUserID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.ResetRequesterUserID()
	_u.mutation.SetRequesterUserID(v)
	return _u
}

// SetNillableRequesterUserID sets the "requester_user_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequesterUserID(v *int64) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequesterUserID(*v)
	}
	return _u
}

// AddRequesterUserID adds value to the "requester_user_id" field.
func (_u *AdminApprovalRequestUpdateOne) AddRequesterUserID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.AddRequesterUserID(v)
	return _u
}

// SetRequesterEmail sets the "requester_email" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequesterEmail(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequesterEmail(v)
	return _u
}

// SetNillableRequesterEmail sets the "requester_email" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequesterEmail(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequesterEmail(*v)
	}
	return _u
}

// SetRequesterIP sets the "requester_ip" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequesterIP(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequesterIP(v)
	return _u
}

// SetNillableRequesterIP sets the "requester_ip" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequesterIP(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequesterIP(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AdminApprovalRequestUpdateOne) SetRequestID(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableRequestID(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDecidedByUserID sets the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdateOne) SetDecidedByUserID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.ResetDecidedByUserID()
	_u.mutation.SetDecidedByUserID(v)
	return _u
}

// SetNillableDecidedByUserID sets the "decided_by_user_id" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableDecidedByUserID(v *int64) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDecidedByUserID(*v)
	}
	return _u
}

// AddDecidedByUserID adds value to the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdateOne) AddDecidedByUserID(v int64) *AdminApprovalRequestUpdateOne {
	_u.mutation.AddDecidedByUserID(v)
	return _u
}

// ClearDecidedByUserID clears the value of the "decided_by_user_id" field.
func (_u *AdminApprovalRequestUpdateOne) ClearDecidedByUserID() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearDecidedByUserID()
	return _u
}

// SetDecidedByEmail sets the "decided_by_email" field.
func (_u *AdminApprovalRequestUpdateOne) SetDecidedByEmail(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetDecidedByEmail(v)
	return _u
}

// SetNillableDecidedByEmail sets the "decided_by_email" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableDecidedByEmail(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDecidedByEmail(*v)
	}
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *AdminApprovalRequestUpdateOne) SetDecidedAt(v time.Time) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableDecidedAt(v *time.Time) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *AdminApprovalRequestUpdateOne) ClearDecidedAt() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetDecisionReason sets the "decision_reason" field.
func (_u *AdminApprovalRequestUpdateOne) SetDecisionReason(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetDecisionReason(v)
	return _u
}

// SetNillableDecisionReason sets the "decision_reason" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableDecisionReason(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDecisionReason(*v)
	}
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *AdminApprovalRequestUpdateOne) SetExecutedAt(v time.Time) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableExecutedAt(v *time.Time) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *AdminApprovalRequestUpdateOne) ClearExecutedAt() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetResultStatusCode sets the "result_status_code" field.
func (_u *AdminApprovalRequestUpdateOne) SetResultStatusCode(v int) *AdminApprovalRequestUpdateOne {
	_u.mutation.ResetResultStatusCode()
	_u.mutation.SetResultStatusCode(v)
	return _u
}

// SetNillableResultStatusCode sets the "result_status_code" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableResultStatusCode(v *int) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetResultStatusCode(*v)
	}
	return _u
}

// AddResultStatusCode adds value to the "result_status_code" field.
func (_u *AdminApprovalRequestUpdateOne) AddResultStatusCode(v int) *AdminApprovalRequestUpdateOne {
	_u.mutation.AddResultStatusCode(v)
	return _u
}

// ClearResultStatusCode clears the value of the "result_status_code" field.
func (_u *AdminApprovalRequestUpdateOne) ClearResultStatusCode() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearResultStatusCode()
	return _u
}

// SetResultBody sets the "result_body" field.
func (_u *AdminApprovalRequestUpdateOne) SetResultBody(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetResultBody(v)
	return _u
}

// SetNillableResultBody sets the "result_body" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableResultBody(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetResultBody(*v)
	}
	return _u
}

// SetResultError sets the "result_error" field.
func (_u *AdminApprovalRequestUpdateOne) SetResultError(v string) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetResultError(v)
	return _u
}

// SetNillableResultError sets the "result_error" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableResultError(v *string) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetResultError(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *AdminApprovalRequestUpdateOne) SetNotifiedAt(v time.Time) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableNotifiedAt(v *time.Time) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *AdminApprovalRequestUpdateOne) ClearNotifiedAt() *AdminApprovalRequestUpdateOne {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminApprovalRequestUpdateOne) SetExpiresAt(v time.Time) *AdminApprovalRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminApprovalRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *AdminApprovalRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AdminApprovalRequestMutation object of the builder.
func (_u *AdminApprovalRequestUpdateOne) Mutation() *AdminApprovalRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminApprovalRequestUpdate builder.
func (_u *AdminApprovalRequestUpdateOne) Where(ps ...predicate.AdminApprovalRequest) *AdminApprovalRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminApprovalRequestUpdateOne) Select(field string, fields ...string) *AdminApprovalRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminApprovalRequest entity.
func (_u *AdminApprovalRequestUpdateOne) Save(ctx context.Context) (*AdminApprovalRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminApprovalRequestUpdateOne) SaveX(ctx context.Context) *AdminApprovalRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminApprovalRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminApprovalRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminApprovalRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminapprovalrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminApprovalRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := adminapprovalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := adminapprovalrequest.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := adminapprovalrequest.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteTemplate(); ok {
		if err := adminapprovalrequest.RouteTemplateValidator(v); err != nil {
			return &ValidationError{Name: "route_template", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.route_template": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := adminapprovalrequest.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := adminapprovalrequest.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodySha256(); ok {
		if err := adminapprovalrequest.RequestBodySha256Validator(v); err != nil {
			return &ValidationError{Name: "request_body_sha256", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := adminapprovalrequest.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetSummary(); ok {
		if err := adminapprovalrequest.TargetSummaryValidator(v); err != nil {
			return &ValidationError{Name: "target_summary", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.target_summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequesterEmail(); ok {
		if err := adminapprovalrequest.RequesterEmailValidator(v); err != nil {
			return &ValidationError{Name: "requester_email", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.requester_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequesterIP(); ok {
		if err := adminapprovalrequest.RequesterIPValidator(v); err != nil {
			return &ValidationError{Name: "requester_ip", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.requester_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adminapprovalrequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecidedByEmail(); ok {
		if err := adminapprovalrequest.DecidedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "decided_by_email", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.decided_by_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultError(); ok {
		if err := adminapprovalrequest.ResultErrorValidator(v); err != nil {
			return &ValidationError{Name: "result_error", err: fmt.Errorf(`ent: validator failed for field "AdminApprovalRequest.result_error": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminApprovalRequestUpdateOne) sqlSave(ctx context.Context) (_node *AdminApprovalRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminapprovalrequest.Table, adminapprovalrequest.Columns, sqlgraph.NewFieldSpec(adminapprovalrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminApprovalRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminapprovalrequest.FieldID)
		for _, f := range fields {
			if !adminapprovalrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminapprovalrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(adminapprovalrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(adminapprovalrequest.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adminapprovalrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteTemplate(); ok {
		_spec.SetField(adminapprovalrequest.FieldRouteTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestQuery(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(adminapprovalrequest.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyEnc(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodyEnc, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyRedacted(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodyRedacted, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodySha256(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(adminapprovalrequest.FieldTargetID, field.TypeInt64, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(adminapprovalrequest.FieldTargetID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TargetSummary(); ok {
		_spec.SetField(adminapprovalrequest.FieldTargetSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterUserID(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequesterUserID(); ok {
		_spec.AddField(adminapprovalrequest.FieldRequesterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequesterEmail(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterIP(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequesterIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adminapprovalrequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedByUserID(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDecidedByUserID(); ok {
		_spec.AddField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.DecidedByUserIDCleared() {
		_spec.ClearField(adminapprovalrequest.FieldDecidedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DecidedByEmail(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedByEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldDecidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionReason(); ok {
		_spec.SetField(adminapprovalrequest.FieldDecisionReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldExecutedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultStatusCode(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultStatusCode(); ok {
		_spec.AddField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt, value)
	}
	if _u.mutation.ResultStatusCodeCleared() {
		_spec.ClearField(adminapprovalrequest.FieldResultStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResultBody(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultError(); ok {
		_spec.SetField(adminapprovalrequest.FieldResultError, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(adminapprovalrequest.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminapprovalrequest.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &AdminApprovalRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminapprovalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
