// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/contenttranslationsource"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ContentTranslationSourceUpdate is the builder for updating ContentTranslationSource entities.
type ContentTranslationSourceUpdate struct {
	config
	hooks    []Hook
	mutation *ContentTranslationSourceMutation
}

// Where appends a list predicates to the ContentTranslationSourceUpdate builder.
func (_u *ContentTranslationSourceUpdate) Where(ps ...predicate.ContentTranslationSource) *ContentTranslationSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *ContentTranslationSourceUpdate) SetNamespace(v string) *ContentTranslationSourceUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdate) SetNillableNamespace(v *string) *ContentTranslationSourceUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *ContentTranslationSourceUpdate) SetSourceHash(v string) *ContentTranslationSourceUpdate {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdate) SetNillableSourceHash(v *string) *ContentTranslationSourceUpdate {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetSourceText sets the "source_text" field.
func (_u *ContentTranslationSourceUpdate) SetSourceText(v string) *ContentTranslationSourceUpdate {
	_u.mutation.SetSourceText(v)
	return _u
}

// SetNillableSourceText sets the "source_text" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdate) SetNillableSourceText(v *string) *ContentTranslationSourceUpdate {
	if v != nil {
		_u.SetSourceText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContentTranslationSourceUpdate) SetUpdatedAt(v time.Time) *ContentTranslationSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdate) SetNillableUpdatedAt(v *time.Time) *ContentTranslationSourceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ContentTranslationSourceMutation object of the builder.
func (_u *ContentTranslationSourceUpdate) Mutation() *ContentTranslationSourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContentTranslationSourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContentTranslationSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContentTranslationSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContentTranslationSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContentTranslationSourceUpdate) check() error {
	if v, ok := _u.mutation.Namespace(); ok {
		if err := contenttranslationsource.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.namespace": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceHash(); ok {
		if err := contenttranslationsource.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.source_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ContentTranslationSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contenttranslationsource.Table, contenttranslationsource.Columns, sqlgraph.NewFieldSpec(contenttranslationsource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(contenttranslationsource.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceText(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contenttranslationsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contenttranslationsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContentTranslationSourceUpdateOne is the builder for updating a single ContentTranslationSource entity.
type ContentTranslationSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContentTranslationSourceMutation
}

// SetNamespace sets the "namespace" field.
func (_u *ContentTranslationSourceUpdateOne) SetNamespace(v string) *ContentTranslationSourceUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdateOne) SetNillableNamespace(v *string) *ContentTranslationSourceUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *ContentTranslationSourceUpdateOne) SetSourceHash(v string) *ContentTranslationSourceUpdateOne {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdateOne) SetNillableSourceHash(v *string) *ContentTranslationSourceUpdateOne {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetSourceText sets the "source_text" field.
func (_u *ContentTranslationSourceUpdateOne) SetSourceText(v string) *ContentTranslationSourceUpdateOne {
	_u.mutation.SetSourceText(v)
	return _u
}

// SetNillableSourceText sets the "source_text" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdateOne) SetNillableSourceText(v *string) *ContentTranslationSourceUpdateOne {
	if v != nil {
		_u.SetSourceText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContentTranslationSourceUpdateOne) SetUpdatedAt(v time.Time) *ContentTranslationSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ContentTranslationSourceUpdateOne) SetNillableUpdatedAt(v *time.Time) *ContentTranslationSourceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ContentTranslationSourceMutation object of the builder.
func (_u *ContentTranslationSourceUpdateOne) Mutation() *ContentTranslationSourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContentTranslationSourceUpdate builder.
func (_u *ContentTranslationSourceUpdateOne) Where(ps ...predicate.ContentTranslationSource) *ContentTranslationSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContentTranslationSourceUpdateOne) Select(field string, fields ...string) *ContentTranslationSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContentTranslationSource entity.
func (_u *ContentTranslationSourceUpdateOne) Save(ctx context.Context) (*ContentTranslationSource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContentTranslationSourceUpdateOne) SaveX(ctx context.Context) *ContentTranslationSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContentTranslationSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContentTranslationSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContentTranslationSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Namespace(); ok {
		if err := contenttranslationsource.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.namespace": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceHash(); ok {
		if err := contenttranslationsource.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.source_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ContentTranslationSourceUpdateOne) sqlSave(ctx context.Context) (_node *ContentTranslationSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contenttranslationsource.Table, contenttranslationsource.Columns, sqlgraph.NewFieldSpec(contenttranslationsource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContentTranslationSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contenttranslationsource.FieldID)
		for _, f := range fields {
			if !contenttranslationsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contenttranslationsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(contenttranslationsource.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceText(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contenttranslationsource.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ContentTranslationSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contenttranslationsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
