// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/contenttranslationsource"
)

// ContentTranslationSource is the model entity for the ContentTranslationSource schema.
type ContentTranslationSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// SourceHash holds the value of the "source_hash" field.
	SourceHash string `json:"source_hash,omitempty"`
	// SourceText holds the value of the "source_text" field.
	SourceText string `json:"source_text,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContentTranslationSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contenttranslationsource.FieldID:
			values[i] = new(sql.NullInt64)
		case contenttranslationsource.FieldNamespace, contenttranslationsource.FieldSourceHash, contenttranslationsource.FieldSourceText:
			values[i] = new(sql.NullString)
		case contenttranslationsource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContentTranslationSource fields.
func (_m *ContentTranslationSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contenttranslationsource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case contenttranslationsource.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case contenttranslationsource.FieldSourceHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_hash", values[i])
			} else if value.Valid {
				_m.SourceHash = value.String
			}
		case contenttranslationsource.FieldSourceText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_text", values[i])
			} else if value.Valid {
				_m.SourceText = value.String
			}
		case contenttranslationsource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContentTranslationSource.
// This includes values selected through modifiers, order, etc.
func (_m *ContentTranslationSource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ContentTranslationSource.
// Note that you need to call ContentTranslationSource.Unwrap() before calling this method if this ContentTranslationSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContentTranslationSource) Update() *ContentTranslationSourceUpdateOne {
	return NewContentTranslationSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContentTranslationSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContentTranslationSource) Unwrap() *ContentTranslationSource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContentTranslationSource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContentTranslationSource) String() string {
	var builder strings.Builder
	builder.WriteString("ContentTranslationSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("source_hash=")
	builder.WriteString(_m.SourceHash)
	builder.WriteString(", ")
	builder.WriteString("source_text=")
	builder.WriteString(_m.SourceText)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContentTranslationSources is a parsable slice of ContentTranslationSource.
type ContentTranslationSources []*ContentTranslationSource
