// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/contenttranslationsource"
)

// ContentTranslationSourceCreate is the builder for creating a ContentTranslationSource entity.
type ContentTranslationSourceCreate struct {
	config
	mutation *ContentTranslationSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNamespace sets the "namespace" field.
func (_c *ContentTranslationSourceCreate) SetNamespace(v string) *ContentTranslationSourceCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetSourceHash sets the "source_hash" field.
func (_c *ContentTranslationSourceCreate) SetSourceHash(v string) *ContentTranslationSourceCreate {
	_c.mutation.SetSourceHash(v)
	return _c
}

// SetSourceText sets the "source_text" field.
func (_c *ContentTranslationSourceCreate) SetSourceText(v string) *ContentTranslationSourceCreate {
	_c.mutation.SetSourceText(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContentTranslationSourceCreate) SetUpdatedAt(v time.Time) *ContentTranslationSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContentTranslationSourceCreate) SetNillableUpdatedAt(v *time.Time) *ContentTranslationSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ContentTranslationSourceMutation object of the builder.
func (_c *ContentTranslationSourceCreate) Mutation() *ContentTranslationSourceMutation {
	return _c.mutation
}

// Save creates the ContentTranslationSource in the database.
func (_c *ContentTranslationSourceCreate) Save(ctx context.Context) (*ContentTranslationSource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContentTranslationSourceCreate) SaveX(ctx context.Context) *ContentTranslationSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentTranslationSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentTranslationSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContentTranslationSourceCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contenttranslationsource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContentTranslationSourceCreate) check() error {
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "ContentTranslationSource.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := contenttranslationsource.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceHash(); !ok {
		return &ValidationError{Name: "source_hash", err: errors.New(`ent: missing required field "ContentTranslationSource.source_hash"`)}
	}
	if v, ok := _c.mutation.SourceHash(); ok {
		if err := contenttranslationsource.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "ContentTranslationSource.source_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceText(); !ok {
		return &ValidationError{Name: "source_text", err: errors.New(`ent: missing required field "ContentTranslationSource.source_text"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ContentTranslationSource.updated_at"`)}
	}
	return nil
}

func (_c *ContentTranslationSourceCreate) sqlSave(ctx context.Context) (*ContentTranslationSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContentTranslationSourceCreate) createSpec() (*ContentTranslationSource, *sqlgraph.CreateSpec) {
	var (
		_node = &ContentTranslationSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contenttranslationsource.Table, sqlgraph.NewFieldSpec(contenttranslationsource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(contenttranslationsource.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.SourceHash(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceHash, field.TypeString, value)
		_node.SourceHash = value
	}
	if value, ok := _c.mutation.SourceText(); ok {
		_spec.SetField(contenttranslationsource.FieldSourceText, field.TypeString, value)
		_node.SourceText = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contenttranslationsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentTranslationSource.Create().
//		SetNamespace(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentTranslationSourceUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentTranslationSourceCreate) OnConflict(opts ...sql.ConflictOption) *ContentTranslationSourceUpsertOne {
	_c.conflict = opts
	return &ContentTranslationSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentTranslationSourceCreate) OnConflictColumns(columns ...string) *ContentTranslationSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentTranslationSourceUpsertOne{
		create: _c,
	}
}

type (
	// ContentTranslationSourceUpsertOne is the builder for "upsert"-ing
	//  one ContentTranslationSource node.
	ContentTranslationSourceUpsertOne struct {
		create *ContentTranslationSourceCreate
	}

	// ContentTranslationSourceUpsert is the "OnConflict" setter.
	ContentTranslationSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetNamespace sets the "namespace" field.
func (u *ContentTranslationSourceUpsert) SetNamespace(v string) *ContentTranslationSourceUpsert {
	u.Set(contenttranslationsource.FieldNamespace, v)
	return u
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsert) UpdateNamespace() *ContentTranslationSourceUpsert {
	u.SetExcluded(contenttranslationsource.FieldNamespace)
	return u
}

// SetSourceHash sets the "source_hash" field.
func (u *ContentTranslationSourceUpsert) SetSourceHash(v string) *ContentTranslationSourceUpsert {
	u.Set(contenttranslationsource.FieldSourceHash, v)
	return u
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsert) UpdateSourceHash() *ContentTranslationSourceUpsert {
	u.SetExcluded(contenttranslationsource.FieldSourceHash)
	return u
}

// SetSourceText sets the "source_text" field.
func (u *ContentTranslationSourceUpsert) SetSourceText(v string) *ContentTranslationSourceUpsert {
	u.Set(contenttranslationsource.FieldSourceText, v)
	return u
}

// UpdateSourceText sets the "source_text" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsert) UpdateSourceText() *ContentTranslationSourceUpsert {
	u.SetExcluded(contenttranslationsource.FieldSourceText)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentTranslationSourceUpsert) SetUpdatedAt(v time.Time) *ContentTranslationSourceUpsert {
	u.Set(contenttranslationsource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsert) UpdateUpdatedAt() *ContentTranslationSourceUpsert {
	u.SetExcluded(contenttranslationsource.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContentTranslationSourceUpsertOne) UpdateNewValues() *ContentTranslationSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContentTranslationSourceUpsertOne) Ignore() *ContentTranslationSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentTranslationSourceUpsertOne) DoNothing() *ContentTranslationSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentTranslationSourceCreate.OnConflict
// documentation for more info.
func (u *ContentTranslationSourceUpsertOne) Update(set func(*ContentTranslationSourceUpsert)) *ContentTranslationSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentTranslationSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetNamespace sets the "namespace" field.
func (u *ContentTranslationSourceUpsertOne) SetNamespace(v string) *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertOne) UpdateNamespace() *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateNamespace()
	})
}

// SetSourceHash sets the "source_hash" field.
func (u *ContentTranslationSourceUpsertOne) SetSourceHash(v string) *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetSourceHash(v)
	})
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertOne) UpdateSourceHash() *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateSourceHash()
	})
}

// SetSourceText sets the "source_text" field.
func (u *ContentTranslationSourceUpsertOne) SetSourceText(v string) *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetSourceText(v)
	})
}

// UpdateSourceText sets the "source_text" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertOne) UpdateSourceText() *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateSourceText()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentTranslationSourceUpsertOne) SetUpdatedAt(v time.Time) *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertOne) UpdateUpdatedAt() *ContentTranslationSourceUpsertOne {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContentTranslationSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContentTranslationSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentTranslationSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContentTranslationSourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContentTranslationSourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContentTranslationSourceCreateBulk is the builder for creating many ContentTranslationSource entities in bulk.
type ContentTranslationSourceCreateBulk struct {
	config
	err      error
	builders []*ContentTranslationSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the ContentTranslationSource entities in the database.
func (_c *ContentTranslationSourceCreateBulk) Save(ctx context.Context) ([]*ContentTranslationSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContentTranslationSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContentTranslationSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContentTranslationSourceCreateBulk) SaveX(ctx context.Context) []*ContentTranslationSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentTranslationSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentTranslationSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentTranslationSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentTranslationSourceUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentTranslationSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContentTranslationSourceUpsertBulk {
	_c.conflict = opts
	return &ContentTranslationSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentTranslationSourceCreateBulk) OnConflictColumns(columns ...string) *ContentTranslationSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentTranslationSourceUpsertBulk{
		create: _c,
	}
}

// ContentTranslationSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of ContentTranslationSource nodes.
type ContentTranslationSourceUpsertBulk struct {
	create *ContentTranslationSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContentTranslationSourceUpsertBulk) UpdateNewValues() *ContentTranslationSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentTranslationSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContentTranslationSourceUpsertBulk) Ignore() *ContentTranslationSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentTranslationSourceUpsertBulk) DoNothing() *ContentTranslationSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentTranslationSourceCreateBulk.OnConflict
// documentation for more info.
func (u *ContentTranslationSourceUpsertBulk) Update(set func(*ContentTranslationSourceUpsert)) *ContentTranslationSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentTranslationSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetNamespace sets the "namespace" field.
func (u *ContentTranslationSourceUpsertBulk) SetNamespace(v string) *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertBulk) UpdateNamespace() *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateNamespace()
	})
}

// SetSourceHash sets the "source_hash" field.
func (u *ContentTranslationSourceUpsertBulk) SetSourceHash(v string) *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetSourceHash(v)
	})
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertBulk) UpdateSourceHash() *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateSourceHash()
	})
}

// SetSourceText sets the "source_text" field.
func (u *ContentTranslationSourceUpsertBulk) SetSourceText(v string) *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetSourceText(v)
	})
}

// UpdateSourceText sets the "source_text" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertBulk) UpdateSourceText() *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateSourceText()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentTranslationSourceUpsertBulk) SetUpdatedAt(v time.Time) *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentTranslationSourceUpsertBulk) UpdateUpdatedAt() *ContentTranslationSourceUpsertBulk {
	return u.Update(func(s *ContentTranslationSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContentTranslationSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContentTranslationSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContentTranslationSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentTranslationSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
