// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupStatusRecordDelete is the builder for deleting a GroupStatusRecord entity.
type GroupStatusRecordDelete struct {
	config
	hooks    []Hook
	mutation *GroupStatusRecordMutation
}

// Where appends a list predicates to the GroupStatusRecordDelete builder.
func (_d *GroupStatusRecordDelete) Where(ps ...predicate.GroupStatusRecord) *GroupStatusRecordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupStatusRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusRecordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupStatusRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupstatusrecord.Table, sqlgraph.NewFieldSpec(groupstatusrecord.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupStatusRecordDeleteOne is the builder for deleting a single GroupStatusRecord entity.
type GroupStatusRecordDeleteOne struct {
	_d *GroupStatusRecordDelete
}

// Where appends a list predicates to the GroupStatusRecordDelete builder.
func (_d *GroupStatusRecordDeleteOne) Where(ps ...predicate.GroupStatusRecord) *GroupStatusRecordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupStatusRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupstatusrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusRecordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
