// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusastracheckrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupStatusAstraCheckRunDelete is the builder for deleting a GroupStatusAstraCheckRun entity.
type GroupStatusAstraCheckRunDelete struct {
	config
	hooks    []Hook
	mutation *GroupStatusAstraCheckRunMutation
}

// Where appends a list predicates to the GroupStatusAstraCheckRunDelete builder.
func (_d *GroupStatusAstraCheckRunDelete) Where(ps ...predicate.GroupStatusAstraCheckRun) *GroupStatusAstraCheckRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupStatusAstraCheckRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusAstraCheckRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupStatusAstraCheckRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupstatusastracheckrun.Table, sqlgraph.NewFieldSpec(groupstatusastracheckrun.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupStatusAstraCheckRunDeleteOne is the builder for deleting a single GroupStatusAstraCheckRun entity.
type GroupStatusAstraCheckRunDeleteOne struct {
	_d *GroupStatusAstraCheckRunDelete
}

// Where appends a list predicates to the GroupStatusAstraCheckRunDelete builder.
func (_d *GroupStatusAstraCheckRunDeleteOne) Where(ps ...predicate.GroupStatusAstraCheckRun) *GroupStatusAstraCheckRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupStatusAstraCheckRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupstatusastracheckrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusAstraCheckRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
