// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusstate"
)

// GroupStatusStateCreate is the builder for creating a GroupStatusState entity.
type GroupStatusStateCreate struct {
	config
	mutation *GroupStatusStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupStatusStateCreate) SetCreatedAt(v time.Time) *GroupStatusStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableCreatedAt(v *time.Time) *GroupStatusStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupStatusStateCreate) SetUpdatedAt(v time.Time) *GroupStatusStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableUpdatedAt(v *time.Time) *GroupStatusStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupStatusStateCreate) SetGroupID(v int64) *GroupStatusStateCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetConfigID sets the "config_id" field.
func (_c *GroupStatusStateCreate) SetConfigID(v int64) *GroupStatusStateCreate {
	_c.mutation.SetConfigID(v)
	return _c
}

// SetLatestStatus sets the "latest_status" field.
func (_c *GroupStatusStateCreate) SetLatestStatus(v string) *GroupStatusStateCreate {
	_c.mutation.SetLatestStatus(v)
	return _c
}

// SetNillableLatestStatus sets the "latest_status" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableLatestStatus(v *string) *GroupStatusStateCreate {
	if v != nil {
		_c.SetLatestStatus(*v)
	}
	return _c
}

// SetStableStatus sets the "stable_status" field.
func (_c *GroupStatusStateCreate) SetStableStatus(v string) *GroupStatusStateCreate {
	_c.mutation.SetStableStatus(v)
	return _c
}

// SetNillableStableStatus sets the "stable_status" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableStableStatus(v *string) *GroupStatusStateCreate {
	if v != nil {
		_c.SetStableStatus(*v)
	}
	return _c
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (_c *GroupStatusStateCreate) SetResponseExcerpt(v string) *GroupStatusStateCreate {
	_c.mutation.SetResponseExcerpt(v)
	return _c
}

// SetNillableResponseExcerpt sets the "response_excerpt" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableResponseExcerpt(v *string) *GroupStatusStateCreate {
	if v != nil {
		_c.SetResponseExcerpt(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *GroupStatusStateCreate) SetLatencyMs(v int64) *GroupStatusStateCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableLatencyMs(v *int64) *GroupStatusStateCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetHTTPCode sets the "http_code" field.
func (_c *GroupStatusStateCreate) SetHTTPCode(v int) *GroupStatusStateCreate {
	_c.mutation.SetHTTPCode(v)
	return _c
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableHTTPCode(v *int) *GroupStatusStateCreate {
	if v != nil {
		_c.SetHTTPCode(*v)
	}
	return _c
}

// SetSubStatus sets the "sub_status" field.
func (_c *GroupStatusStateCreate) SetSubStatus(v string) *GroupStatusStateCreate {
	_c.mutation.SetSubStatus(v)
	return _c
}

// SetNillableSubStatus sets the "sub_status" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableSubStatus(v *string) *GroupStatusStateCreate {
	if v != nil {
		_c.SetSubStatus(*v)
	}
	return _c
}

// SetErrorDetail sets the "error_detail" field.
func (_c *GroupStatusStateCreate) SetErrorDetail(v string) *GroupStatusStateCreate {
	_c.mutation.SetErrorDetail(v)
	return _c
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableErrorDetail(v *string) *GroupStatusStateCreate {
	if v != nil {
		_c.SetErrorDetail(*v)
	}
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *GroupStatusStateCreate) SetObservedAt(v time.Time) *GroupStatusStateCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableObservedAt(v *time.Time) *GroupStatusStateCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (_c *GroupStatusStateCreate) SetConsecutiveDown(v int) *GroupStatusStateCreate {
	_c.mutation.SetConsecutiveDown(v)
	return _c
}

// SetNillableConsecutiveDown sets the "consecutive_down" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableConsecutiveDown(v *int) *GroupStatusStateCreate {
	if v != nil {
		_c.SetConsecutiveDown(*v)
	}
	return _c
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (_c *GroupStatusStateCreate) SetConsecutiveNonDown(v int) *GroupStatusStateCreate {
	_c.mutation.SetConsecutiveNonDown(v)
	return _c
}

// SetNillableConsecutiveNonDown sets the "consecutive_non_down" field if the given value is not nil.
func (_c *GroupStatusStateCreate) SetNillableConsecutiveNonDown(v *int) *GroupStatusStateCreate {
	if v != nil {
		_c.SetConsecutiveNonDown(*v)
	}
	return _c
}

// Mutation returns the GroupStatusStateMutation object of the builder.
func (_c *GroupStatusStateCreate) Mutation() *GroupStatusStateMutation {
	return _c.mutation
}

// Save creates the GroupStatusState in the database.
func (_c *GroupStatusStateCreate) Save(ctx context.Context) (*GroupStatusState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupStatusStateCreate) SaveX(ctx context.Context) *GroupStatusState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupStatusStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupStatusStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupStatusStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupstatusstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groupstatusstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LatestStatus(); !ok {
		v := groupstatusstate.DefaultLatestStatus
		_c.mutation.SetLatestStatus(v)
	}
	if _, ok := _c.mutation.StableStatus(); !ok {
		v := groupstatusstate.DefaultStableStatus
		_c.mutation.SetStableStatus(v)
	}
	if _, ok := _c.mutation.SubStatus(); !ok {
		v := groupstatusstate.DefaultSubStatus
		_c.mutation.SetSubStatus(v)
	}
	if _, ok := _c.mutation.ConsecutiveDown(); !ok {
		v := groupstatusstate.DefaultConsecutiveDown
		_c.mutation.SetConsecutiveDown(v)
	}
	if _, ok := _c.mutation.ConsecutiveNonDown(); !ok {
		v := groupstatusstate.DefaultConsecutiveNonDown
		_c.mutation.SetConsecutiveNonDown(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupStatusStateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupStatusState.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupStatusState.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupStatusState.group_id"`)}
	}
	if _, ok := _c.mutation.ConfigID(); !ok {
		return &ValidationError{Name: "config_id", err: errors.New(`ent: missing required field "GroupStatusState.config_id"`)}
	}
	if _, ok := _c.mutation.LatestStatus(); !ok {
		return &ValidationError{Name: "latest_status", err: errors.New(`ent: missing required field "GroupStatusState.latest_status"`)}
	}
	if _, ok := _c.mutation.StableStatus(); !ok {
		return &ValidationError{Name: "stable_status", err: errors.New(`ent: missing required field "GroupStatusState.stable_status"`)}
	}
	if _, ok := _c.mutation.SubStatus(); !ok {
		return &ValidationError{Name: "sub_status", err: errors.New(`ent: missing required field "GroupStatusState.sub_status"`)}
	}
	if _, ok := _c.mutation.ConsecutiveDown(); !ok {
		return &ValidationError{Name: "consecutive_down", err: errors.New(`ent: missing required field "GroupStatusState.consecutive_down"`)}
	}
	if _, ok := _c.mutation.ConsecutiveNonDown(); !ok {
		return &ValidationError{Name: "consecutive_non_down", err: errors.New(`ent: missing required field "GroupStatusState.consecutive_non_down"`)}
	}
	return nil
}

func (_c *GroupStatusStateCreate) sqlSave(ctx context.Context) (*GroupStatusState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupStatusStateCreate) createSpec() (*GroupStatusState, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupStatusState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupstatusstate.Table, sqlgraph.NewFieldSpec(groupstatusstate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupstatusstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupstatusstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(groupstatusstate.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusstate.FieldConfigID, field.TypeInt64, value)
		_node.ConfigID = value
	}
	if value, ok := _c.mutation.LatestStatus(); ok {
		_spec.SetField(groupstatusstate.FieldLatestStatus, field.TypeString, value)
		_node.LatestStatus = value
	}
	if value, ok := _c.mutation.StableStatus(); ok {
		_spec.SetField(groupstatusstate.FieldStableStatus, field.TypeString, value)
		_node.StableStatus = value
	}
	if value, ok := _c.mutation.ResponseExcerpt(); ok {
		_spec.SetField(groupstatusstate.FieldResponseExcerpt, field.TypeString, value)
		_node.ResponseExcerpt = &value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusstate.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusstate.FieldHTTPCode, field.TypeInt, value)
		_node.HTTPCode = &value
	}
	if value, ok := _c.mutation.SubStatus(); ok {
		_spec.SetField(groupstatusstate.FieldSubStatus, field.TypeString, value)
		_node.SubStatus = value
	}
	if value, ok := _c.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusstate.FieldErrorDetail, field.TypeString, value)
		_node.ErrorDetail = &value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusstate.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = &value
	}
	if value, ok := _c.mutation.ConsecutiveDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveDown, field.TypeInt, value)
		_node.ConsecutiveDown = value
	}
	if value, ok := _c.mutation.ConsecutiveNonDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveNonDown, field.TypeInt, value)
		_node.ConsecutiveNonDown = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupStatusState.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupStatusStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupStatusStateCreate) OnConflict(opts ...sql.ConflictOption) *GroupStatusStateUpsertOne {
	_c.conflict = opts
	return &GroupStatusStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupStatusStateCreate) OnConflictColumns(columns ...string) *GroupStatusStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupStatusStateUpsertOne{
		create: _c,
	}
}

type (
	// GroupStatusStateUpsertOne is the builder for "upsert"-ing
	//  one GroupStatusState node.
	GroupStatusStateUpsertOne struct {
		create *GroupStatusStateCreate
	}

	// GroupStatusStateUpsert is the "OnConflict" setter.
	GroupStatusStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupStatusStateUpsert) SetUpdatedAt(v time.Time) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateUpdatedAt() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupStatusStateUpsert) SetGroupID(v int64) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateGroupID() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusStateUpsert) AddGroupID(v int64) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldGroupID, v)
	return u
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusStateUpsert) SetConfigID(v int64) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldConfigID, v)
	return u
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateConfigID() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldConfigID)
	return u
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusStateUpsert) AddConfigID(v int64) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldConfigID, v)
	return u
}

// SetLatestStatus sets the "latest_status" field.
func (u *GroupStatusStateUpsert) SetLatestStatus(v string) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldLatestStatus, v)
	return u
}

// UpdateLatestStatus sets the "latest_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateLatestStatus() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldLatestStatus)
	return u
}

// SetStableStatus sets the "stable_status" field.
func (u *GroupStatusStateUpsert) SetStableStatus(v string) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldStableStatus, v)
	return u
}

// UpdateStableStatus sets the "stable_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateStableStatus() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldStableStatus)
	return u
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (u *GroupStatusStateUpsert) SetResponseExcerpt(v string) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldResponseExcerpt, v)
	return u
}

// UpdateResponseExcerpt sets the "response_excerpt" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateResponseExcerpt() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldResponseExcerpt)
	return u
}

// ClearResponseExcerpt clears the value of the "response_excerpt" field.
func (u *GroupStatusStateUpsert) ClearResponseExcerpt() *GroupStatusStateUpsert {
	u.SetNull(groupstatusstate.FieldResponseExcerpt)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusStateUpsert) SetLatencyMs(v int64) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateLatencyMs() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusStateUpsert) AddLatencyMs(v int64) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusStateUpsert) ClearLatencyMs() *GroupStatusStateUpsert {
	u.SetNull(groupstatusstate.FieldLatencyMs)
	return u
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusStateUpsert) SetHTTPCode(v int) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldHTTPCode, v)
	return u
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateHTTPCode() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldHTTPCode)
	return u
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusStateUpsert) AddHTTPCode(v int) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldHTTPCode, v)
	return u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusStateUpsert) ClearHTTPCode() *GroupStatusStateUpsert {
	u.SetNull(groupstatusstate.FieldHTTPCode)
	return u
}

// SetSubStatus sets the "sub_status" field.
func (u *GroupStatusStateUpsert) SetSubStatus(v string) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldSubStatus, v)
	return u
}

// UpdateSubStatus sets the "sub_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateSubStatus() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldSubStatus)
	return u
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusStateUpsert) SetErrorDetail(v string) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldErrorDetail, v)
	return u
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateErrorDetail() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldErrorDetail)
	return u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusStateUpsert) ClearErrorDetail() *GroupStatusStateUpsert {
	u.SetNull(groupstatusstate.FieldErrorDetail)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusStateUpsert) SetObservedAt(v time.Time) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateObservedAt() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldObservedAt)
	return u
}

// ClearObservedAt clears the value of the "observed_at" field.
func (u *GroupStatusStateUpsert) ClearObservedAt() *GroupStatusStateUpsert {
	u.SetNull(groupstatusstate.FieldObservedAt)
	return u
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (u *GroupStatusStateUpsert) SetConsecutiveDown(v int) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldConsecutiveDown, v)
	return u
}

// UpdateConsecutiveDown sets the "consecutive_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateConsecutiveDown() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldConsecutiveDown)
	return u
}

// AddConsecutiveDown adds v to the "consecutive_down" field.
func (u *GroupStatusStateUpsert) AddConsecutiveDown(v int) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldConsecutiveDown, v)
	return u
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (u *GroupStatusStateUpsert) SetConsecutiveNonDown(v int) *GroupStatusStateUpsert {
	u.Set(groupstatusstate.FieldConsecutiveNonDown, v)
	return u
}

// UpdateConsecutiveNonDown sets the "consecutive_non_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsert) UpdateConsecutiveNonDown() *GroupStatusStateUpsert {
	u.SetExcluded(groupstatusstate.FieldConsecutiveNonDown)
	return u
}

// AddConsecutiveNonDown adds v to the "consecutive_non_down" field.
func (u *GroupStatusStateUpsert) AddConsecutiveNonDown(v int) *GroupStatusStateUpsert {
	u.Add(groupstatusstate.FieldConsecutiveNonDown, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupStatusStateUpsertOne) UpdateNewValues() *GroupStatusStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupstatusstate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupStatusStateUpsertOne) Ignore() *GroupStatusStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupStatusStateUpsertOne) DoNothing() *GroupStatusStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupStatusStateCreate.OnConflict
// documentation for more info.
func (u *GroupStatusStateUpsertOne) Update(set func(*GroupStatusStateUpsert)) *GroupStatusStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupStatusStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupStatusStateUpsertOne) SetUpdatedAt(v time.Time) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateUpdatedAt() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupStatusStateUpsertOne) SetGroupID(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusStateUpsertOne) AddGroupID(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateGroupID() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateGroupID()
	})
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusStateUpsertOne) SetConfigID(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConfigID(v)
	})
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusStateUpsertOne) AddConfigID(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateConfigID() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConfigID()
	})
}

// SetLatestStatus sets the "latest_status" field.
func (u *GroupStatusStateUpsertOne) SetLatestStatus(v string) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetLatestStatus(v)
	})
}

// UpdateLatestStatus sets the "latest_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateLatestStatus() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateLatestStatus()
	})
}

// SetStableStatus sets the "stable_status" field.
func (u *GroupStatusStateUpsertOne) SetStableStatus(v string) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetStableStatus(v)
	})
}

// UpdateStableStatus sets the "stable_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateStableStatus() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateStableStatus()
	})
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (u *GroupStatusStateUpsertOne) SetResponseExcerpt(v string) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetResponseExcerpt(v)
	})
}

// UpdateResponseExcerpt sets the "response_excerpt" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateResponseExcerpt() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateResponseExcerpt()
	})
}

// ClearResponseExcerpt clears the value of the "response_excerpt" field.
func (u *GroupStatusStateUpsertOne) ClearResponseExcerpt() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearResponseExcerpt()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusStateUpsertOne) SetLatencyMs(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusStateUpsertOne) AddLatencyMs(v int64) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateLatencyMs() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusStateUpsertOne) ClearLatencyMs() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearLatencyMs()
	})
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusStateUpsertOne) SetHTTPCode(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetHTTPCode(v)
	})
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusStateUpsertOne) AddHTTPCode(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddHTTPCode(v)
	})
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateHTTPCode() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateHTTPCode()
	})
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusStateUpsertOne) ClearHTTPCode() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearHTTPCode()
	})
}

// SetSubStatus sets the "sub_status" field.
func (u *GroupStatusStateUpsertOne) SetSubStatus(v string) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetSubStatus(v)
	})
}

// UpdateSubStatus sets the "sub_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateSubStatus() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateSubStatus()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusStateUpsertOne) SetErrorDetail(v string) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateErrorDetail() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusStateUpsertOne) ClearErrorDetail() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearErrorDetail()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusStateUpsertOne) SetObservedAt(v time.Time) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateObservedAt() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateObservedAt()
	})
}

// ClearObservedAt clears the value of the "observed_at" field.
func (u *GroupStatusStateUpsertOne) ClearObservedAt() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearObservedAt()
	})
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (u *GroupStatusStateUpsertOne) SetConsecutiveDown(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConsecutiveDown(v)
	})
}

// AddConsecutiveDown adds v to the "consecutive_down" field.
func (u *GroupStatusStateUpsertOne) AddConsecutiveDown(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConsecutiveDown(v)
	})
}

// UpdateConsecutiveDown sets the "consecutive_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateConsecutiveDown() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConsecutiveDown()
	})
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (u *GroupStatusStateUpsertOne) SetConsecutiveNonDown(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConsecutiveNonDown(v)
	})
}

// AddConsecutiveNonDown adds v to the "consecutive_non_down" field.
func (u *GroupStatusStateUpsertOne) AddConsecutiveNonDown(v int) *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConsecutiveNonDown(v)
	})
}

// UpdateConsecutiveNonDown sets the "consecutive_non_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsertOne) UpdateConsecutiveNonDown() *GroupStatusStateUpsertOne {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConsecutiveNonDown()
	})
}

// Exec executes the query.
func (u *GroupStatusStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupStatusStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupStatusStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupStatusStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupStatusStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupStatusStateCreateBulk is the builder for creating many GroupStatusState entities in bulk.
type GroupStatusStateCreateBulk struct {
	config
	err      error
	builders []*GroupStatusStateCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupStatusState entities in the database.
func (_c *GroupStatusStateCreateBulk) Save(ctx context.Context) ([]*GroupStatusState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupStatusState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupStatusStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupStatusStateCreateBulk) SaveX(ctx context.Context) []*GroupStatusState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupStatusStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupStatusStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupStatusState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupStatusStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupStatusStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupStatusStateUpsertBulk {
	_c.conflict = opts
	return &GroupStatusStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupStatusStateCreateBulk) OnConflictColumns(columns ...string) *GroupStatusStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupStatusStateUpsertBulk{
		create: _c,
	}
}

// GroupStatusStateUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupStatusState nodes.
type GroupStatusStateUpsertBulk struct {
	create *GroupStatusStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupStatusStateUpsertBulk) UpdateNewValues() *GroupStatusStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupstatusstate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupStatusState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupStatusStateUpsertBulk) Ignore() *GroupStatusStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupStatusStateUpsertBulk) DoNothing() *GroupStatusStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupStatusStateCreateBulk.OnConflict
// documentation for more info.
func (u *GroupStatusStateUpsertBulk) Update(set func(*GroupStatusStateUpsert)) *GroupStatusStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupStatusStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupStatusStateUpsertBulk) SetUpdatedAt(v time.Time) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateUpdatedAt() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupStatusStateUpsertBulk) SetGroupID(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusStateUpsertBulk) AddGroupID(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateGroupID() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateGroupID()
	})
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusStateUpsertBulk) SetConfigID(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConfigID(v)
	})
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusStateUpsertBulk) AddConfigID(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateConfigID() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConfigID()
	})
}

// SetLatestStatus sets the "latest_status" field.
func (u *GroupStatusStateUpsertBulk) SetLatestStatus(v string) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetLatestStatus(v)
	})
}

// UpdateLatestStatus sets the "latest_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateLatestStatus() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateLatestStatus()
	})
}

// SetStableStatus sets the "stable_status" field.
func (u *GroupStatusStateUpsertBulk) SetStableStatus(v string) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetStableStatus(v)
	})
}

// UpdateStableStatus sets the "stable_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateStableStatus() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateStableStatus()
	})
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (u *GroupStatusStateUpsertBulk) SetResponseExcerpt(v string) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetResponseExcerpt(v)
	})
}

// UpdateResponseExcerpt sets the "response_excerpt" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateResponseExcerpt() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateResponseExcerpt()
	})
}

// ClearResponseExcerpt clears the value of the "response_excerpt" field.
func (u *GroupStatusStateUpsertBulk) ClearResponseExcerpt() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearResponseExcerpt()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusStateUpsertBulk) SetLatencyMs(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusStateUpsertBulk) AddLatencyMs(v int64) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateLatencyMs() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusStateUpsertBulk) ClearLatencyMs() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearLatencyMs()
	})
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusStateUpsertBulk) SetHTTPCode(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetHTTPCode(v)
	})
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusStateUpsertBulk) AddHTTPCode(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddHTTPCode(v)
	})
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateHTTPCode() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateHTTPCode()
	})
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusStateUpsertBulk) ClearHTTPCode() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearHTTPCode()
	})
}

// SetSubStatus sets the "sub_status" field.
func (u *GroupStatusStateUpsertBulk) SetSubStatus(v string) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetSubStatus(v)
	})
}

// UpdateSubStatus sets the "sub_status" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateSubStatus() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateSubStatus()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusStateUpsertBulk) SetErrorDetail(v string) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateErrorDetail() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusStateUpsertBulk) ClearErrorDetail() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearErrorDetail()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusStateUpsertBulk) SetObservedAt(v time.Time) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateObservedAt() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateObservedAt()
	})
}

// ClearObservedAt clears the value of the "observed_at" field.
func (u *GroupStatusStateUpsertBulk) ClearObservedAt() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.ClearObservedAt()
	})
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (u *GroupStatusStateUpsertBulk) SetConsecutiveDown(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConsecutiveDown(v)
	})
}

// AddConsecutiveDown adds v to the "consecutive_down" field.
func (u *GroupStatusStateUpsertBulk) AddConsecutiveDown(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConsecutiveDown(v)
	})
}

// UpdateConsecutiveDown sets the "consecutive_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateConsecutiveDown() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConsecutiveDown()
	})
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (u *GroupStatusStateUpsertBulk) SetConsecutiveNonDown(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.SetConsecutiveNonDown(v)
	})
}

// AddConsecutiveNonDown adds v to the "consecutive_non_down" field.
func (u *GroupStatusStateUpsertBulk) AddConsecutiveNonDown(v int) *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.AddConsecutiveNonDown(v)
	})
}

// UpdateConsecutiveNonDown sets the "consecutive_non_down" field to the value that was provided on create.
func (u *GroupStatusStateUpsertBulk) UpdateConsecutiveNonDown() *GroupStatusStateUpsertBulk {
	return u.Update(func(s *GroupStatusStateUpsert) {
		s.UpdateConsecutiveNonDown()
	})
}

// Exec executes the query.
func (u *GroupStatusStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupStatusStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupStatusStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupStatusStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
