// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupStatusEventUpdate is the builder for updating GroupStatusEvent entities.
type GroupStatusEventUpdate struct {
	config
	hooks    []Hook
	mutation *GroupStatusEventMutation
}

// Where appends a list predicates to the GroupStatusEventUpdate builder.
func (_u *GroupStatusEventUpdate) Where(ps ...predicate.GroupStatusEvent) *GroupStatusEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupStatusEventUpdate) SetGroupID(v int64) *GroupStatusEventUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableGroupID(v *int64) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupStatusEventUpdate) AddGroupID(v int64) *GroupStatusEventUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *GroupStatusEventUpdate) SetConfigID(v int64) *GroupStatusEventUpdate {
	_u.mutation.ResetConfigID()
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableConfigID(v *int64) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// AddConfigID adds value to the "config_id" field.
func (_u *GroupStatusEventUpdate) AddConfigID(v int64) *GroupStatusEventUpdate {
	_u.mutation.AddConfigID(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *GroupStatusEventUpdate) SetEventType(v string) *GroupStatusEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableEventType(v *string) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *GroupStatusEventUpdate) SetFromStatus(v string) *GroupStatusEventUpdate {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableFromStatus(v *string) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *GroupStatusEventUpdate) SetToStatus(v string) *GroupStatusEventUpdate {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableToStatus(v *string) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GroupStatusEventUpdate) SetLatencyMs(v int64) *GroupStatusEventUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableLatencyMs(v *int64) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GroupStatusEventUpdate) AddLatencyMs(v int64) *GroupStatusEventUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *GroupStatusEventUpdate) ClearLatencyMs() *GroupStatusEventUpdate {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetHTTPCode sets the "http_code" field.
func (_u *GroupStatusEventUpdate) SetHTTPCode(v int) *GroupStatusEventUpdate {
	_u.mutation.ResetHTTPCode()
	_u.mutation.SetHTTPCode(v)
	return _u
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableHTTPCode(v *int) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetHTTPCode(*v)
	}
	return _u
}

// AddHTTPCode adds value to the "http_code" field.
func (_u *GroupStatusEventUpdate) AddHTTPCode(v int) *GroupStatusEventUpdate {
	_u.mutation.AddHTTPCode(v)
	return _u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (_u *GroupStatusEventUpdate) ClearHTTPCode() *GroupStatusEventUpdate {
	_u.mutation.ClearHTTPCode()
	return _u
}

// SetSubStatus sets the "sub_status" field.
func (_u *GroupStatusEventUpdate) SetSubStatus(v string) *GroupStatusEventUpdate {
	_u.mutation.SetSubStatus(v)
	return _u
}

// SetNillableSubStatus sets the "sub_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableSubStatus(v *string) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetSubStatus(*v)
	}
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *GroupStatusEventUpdate) SetErrorDetail(v string) *GroupStatusEventUpdate {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableErrorDetail(v *string) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *GroupStatusEventUpdate) ClearErrorDetail() *GroupStatusEventUpdate {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupStatusEventUpdate) SetObservedAt(v time.Time) *GroupStatusEventUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupStatusEventUpdate) SetNillableObservedAt(v *time.Time) *GroupStatusEventUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// Mutation returns the GroupStatusEventMutation object of the builder.
func (_u *GroupStatusEventUpdate) Mutation() *GroupStatusEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupStatusEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupStatusEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupStatusEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupStatusEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GroupStatusEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(groupstatusevent.Table, groupstatusevent.Columns, sqlgraph.NewFieldSpec(groupstatusevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupstatusevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupstatusevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusevent.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigID(); ok {
		_spec.AddField(groupstatusevent.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(groupstatusevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(groupstatusevent.FieldFromStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(groupstatusevent.FieldToStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusevent.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(groupstatusevent.FieldLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(groupstatusevent.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusevent.FieldHTTPCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPCode(); ok {
		_spec.AddField(groupstatusevent.FieldHTTPCode, field.TypeInt, value)
	}
	if _u.mutation.HTTPCodeCleared() {
		_spec.ClearField(groupstatusevent.FieldHTTPCode, field.TypeInt)
	}
	if value, ok := _u.mutation.SubStatus(); ok {
		_spec.SetField(groupstatusevent.FieldSubStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusevent.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(groupstatusevent.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusevent.FieldObservedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupstatusevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupStatusEventUpdateOne is the builder for updating a single GroupStatusEvent entity.
type GroupStatusEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupStatusEventMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupStatusEventUpdateOne) SetGroupID(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableGroupID(v *int64) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupStatusEventUpdateOne) AddGroupID(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *GroupStatusEventUpdateOne) SetConfigID(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.ResetConfigID()
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableConfigID(v *int64) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// AddConfigID adds value to the "config_id" field.
func (_u *GroupStatusEventUpdateOne) AddConfigID(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.AddConfigID(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *GroupStatusEventUpdateOne) SetEventType(v string) *GroupStatusEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableEventType(v *string) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *GroupStatusEventUpdateOne) SetFromStatus(v string) *GroupStatusEventUpdateOne {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableFromStatus(v *string) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *GroupStatusEventUpdateOne) SetToStatus(v string) *GroupStatusEventUpdateOne {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableToStatus(v *string) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GroupStatusEventUpdateOne) SetLatencyMs(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableLatencyMs(v *int64) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GroupStatusEventUpdateOne) AddLatencyMs(v int64) *GroupStatusEventUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *GroupStatusEventUpdateOne) ClearLatencyMs() *GroupStatusEventUpdateOne {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetHTTPCode sets the "http_code" field.
func (_u *GroupStatusEventUpdateOne) SetHTTPCode(v int) *GroupStatusEventUpdateOne {
	_u.mutation.ResetHTTPCode()
	_u.mutation.SetHTTPCode(v)
	return _u
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableHTTPCode(v *int) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetHTTPCode(*v)
	}
	return _u
}

// AddHTTPCode adds value to the "http_code" field.
func (_u *GroupStatusEventUpdateOne) AddHTTPCode(v int) *GroupStatusEventUpdateOne {
	_u.mutation.AddHTTPCode(v)
	return _u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (_u *GroupStatusEventUpdateOne) ClearHTTPCode() *GroupStatusEventUpdateOne {
	_u.mutation.ClearHTTPCode()
	return _u
}

// SetSubStatus sets the "sub_status" field.
func (_u *GroupStatusEventUpdateOne) SetSubStatus(v string) *GroupStatusEventUpdateOne {
	_u.mutation.SetSubStatus(v)
	return _u
}

// SetNillableSubStatus sets the "sub_status" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableSubStatus(v *string) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetSubStatus(*v)
	}
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *GroupStatusEventUpdateOne) SetErrorDetail(v string) *GroupStatusEventUpdateOne {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableErrorDetail(v *string) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *GroupStatusEventUpdateOne) ClearErrorDetail() *GroupStatusEventUpdateOne {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupStatusEventUpdateOne) SetObservedAt(v time.Time) *GroupStatusEventUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupStatusEventUpdateOne) SetNillableObservedAt(v *time.Time) *GroupStatusEventUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// Mutation returns the GroupStatusEventMutation object of the builder.
func (_u *GroupStatusEventUpdateOne) Mutation() *GroupStatusEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupStatusEventUpdate builder.
func (_u *GroupStatusEventUpdateOne) Where(ps ...predicate.GroupStatusEvent) *GroupStatusEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupStatusEventUpdateOne) Select(field string, fields ...string) *GroupStatusEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupStatusEvent entity.
func (_u *GroupStatusEventUpdateOne) Save(ctx context.Context) (*GroupStatusEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupStatusEventUpdateOne) SaveX(ctx context.Context) *GroupStatusEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupStatusEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupStatusEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GroupStatusEventUpdateOne) sqlSave(ctx context.Context) (_node *GroupStatusEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(groupstatusevent.Table, groupstatusevent.Columns, sqlgraph.NewFieldSpec(groupstatusevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupStatusEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupstatusevent.FieldID)
		for _, f := range fields {
			if !groupstatusevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupstatusevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupstatusevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupstatusevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusevent.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigID(); ok {
		_spec.AddField(groupstatusevent.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(groupstatusevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(groupstatusevent.FieldFromStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(groupstatusevent.FieldToStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusevent.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(groupstatusevent.FieldLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(groupstatusevent.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusevent.FieldHTTPCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPCode(); ok {
		_spec.AddField(groupstatusevent.FieldHTTPCode, field.TypeInt, value)
	}
	if _u.mutation.HTTPCodeCleared() {
		_spec.ClearField(groupstatusevent.FieldHTTPCode, field.TypeInt)
	}
	if value, ok := _u.mutation.SubStatus(); ok {
		_spec.SetField(groupstatusevent.FieldSubStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusevent.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(groupstatusevent.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusevent.FieldObservedAt, field.TypeTime, value)
	}
	_node = &GroupStatusEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupstatusevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
