// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupStatusStateUpdate is the builder for updating GroupStatusState entities.
type GroupStatusStateUpdate struct {
	config
	hooks    []Hook
	mutation *GroupStatusStateMutation
}

// Where appends a list predicates to the GroupStatusStateUpdate builder.
func (_u *GroupStatusStateUpdate) Where(ps ...predicate.GroupStatusState) *GroupStatusStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupStatusStateUpdate) SetUpdatedAt(v time.Time) *GroupStatusStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupStatusStateUpdate) SetGroupID(v int64) *GroupStatusStateUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableGroupID(v *int64) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupStatusStateUpdate) AddGroupID(v int64) *GroupStatusStateUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *GroupStatusStateUpdate) SetConfigID(v int64) *GroupStatusStateUpdate {
	_u.mutation.ResetConfigID()
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableConfigID(v *int64) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// AddConfigID adds value to the "config_id" field.
func (_u *GroupStatusStateUpdate) AddConfigID(v int64) *GroupStatusStateUpdate {
	_u.mutation.AddConfigID(v)
	return _u
}

// SetLatestStatus sets the "latest_status" field.
func (_u *GroupStatusStateUpdate) SetLatestStatus(v string) *GroupStatusStateUpdate {
	_u.mutation.SetLatestStatus(v)
	return _u
}

// SetNillableLatestStatus sets the "latest_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableLatestStatus(v *string) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetLatestStatus(*v)
	}
	return _u
}

// SetStableStatus sets the "stable_status" field.
func (_u *GroupStatusStateUpdate) SetStableStatus(v string) *GroupStatusStateUpdate {
	_u.mutation.SetStableStatus(v)
	return _u
}

// SetNillableStableStatus sets the "stable_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableStableStatus(v *string) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetStableStatus(*v)
	}
	return _u
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (_u *GroupStatusStateUpdate) SetResponseExcerpt(v string) *GroupStatusStateUpdate {
	_u.mutation.SetResponseExcerpt(v)
	return _u
}

// SetNillableResponseExcerpt sets the "response_excerpt" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableResponseExcerpt(v *string) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetResponseExcerpt(*v)
	}
	return _u
}

// ClearResponseExcerpt clears the value of the "response_excerpt" field.
func (_u *GroupStatusStateUpdate) ClearResponseExcerpt() *GroupStatusStateUpdate {
	_u.mutation.ClearResponseExcerpt()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GroupStatusStateUpdate) SetLatencyMs(v int64) *GroupStatusStateUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableLatencyMs(v *int64) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GroupStatusStateUpdate) AddLatencyMs(v int64) *GroupStatusStateUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *GroupStatusStateUpdate) ClearLatencyMs() *GroupStatusStateUpdate {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetHTTPCode sets the "http_code" field.
func (_u *GroupStatusStateUpdate) SetHTTPCode(v int) *GroupStatusStateUpdate {
	_u.mutation.ResetHTTPCode()
	_u.mutation.SetHTTPCode(v)
	return _u
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableHTTPCode(v *int) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetHTTPCode(*v)
	}
	return _u
}

// AddHTTPCode adds value to the "http_code" field.
func (_u *GroupStatusStateUpdate) AddHTTPCode(v int) *GroupStatusStateUpdate {
	_u.mutation.AddHTTPCode(v)
	return _u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (_u *GroupStatusStateUpdate) ClearHTTPCode() *GroupStatusStateUpdate {
	_u.mutation.ClearHTTPCode()
	return _u
}

// SetSubStatus sets the "sub_status" field.
func (_u *GroupStatusStateUpdate) SetSubStatus(v string) *GroupStatusStateUpdate {
	_u.mutation.SetSubStatus(v)
	return _u
}

// SetNillableSubStatus sets the "sub_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableSubStatus(v *string) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetSubStatus(*v)
	}
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *GroupStatusStateUpdate) SetErrorDetail(v string) *GroupStatusStateUpdate {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableErrorDetail(v *string) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *GroupStatusStateUpdate) ClearErrorDetail() *GroupStatusStateUpdate {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupStatusStateUpdate) SetObservedAt(v time.Time) *GroupStatusStateUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableObservedAt(v *time.Time) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// ClearObservedAt clears the value of the "observed_at" field.
func (_u *GroupStatusStateUpdate) ClearObservedAt() *GroupStatusStateUpdate {
	_u.mutation.ClearObservedAt()
	return _u
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (_u *GroupStatusStateUpdate) SetConsecutiveDown(v int) *GroupStatusStateUpdate {
	_u.mutation.ResetConsecutiveDown()
	_u.mutation.SetConsecutiveDown(v)
	return _u
}

// SetNillableConsecutiveDown sets the "consecutive_down" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableConsecutiveDown(v *int) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetConsecutiveDown(*v)
	}
	return _u
}

// AddConsecutiveDown adds value to the "consecutive_down" field.
func (_u *GroupStatusStateUpdate) AddConsecutiveDown(v int) *GroupStatusStateUpdate {
	_u.mutation.AddConsecutiveDown(v)
	return _u
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (_u *GroupStatusStateUpdate) SetConsecutiveNonDown(v int) *GroupStatusStateUpdate {
	_u.mutation.ResetConsecutiveNonDown()
	_u.mutation.SetConsecutiveNonDown(v)
	return _u
}

// SetNillableConsecutiveNonDown sets the "consecutive_non_down" field if the given value is not nil.
func (_u *GroupStatusStateUpdate) SetNillableConsecutiveNonDown(v *int) *GroupStatusStateUpdate {
	if v != nil {
		_u.SetConsecutiveNonDown(*v)
	}
	return _u
}

// AddConsecutiveNonDown adds value to the "consecutive_non_down" field.
func (_u *GroupStatusStateUpdate) AddConsecutiveNonDown(v int) *GroupStatusStateUpdate {
	_u.mutation.AddConsecutiveNonDown(v)
	return _u
}

// Mutation returns the GroupStatusStateMutation object of the builder.
func (_u *GroupStatusStateUpdate) Mutation() *GroupStatusStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupStatusStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupStatusStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupStatusStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupStatusStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupStatusStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupstatusstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GroupStatusStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(groupstatusstate.Table, groupstatusstate.Columns, sqlgraph.NewFieldSpec(groupstatusstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupstatusstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupstatusstate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupstatusstate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusstate.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigID(); ok {
		_spec.AddField(groupstatusstate.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LatestStatus(); ok {
		_spec.SetField(groupstatusstate.FieldLatestStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StableStatus(); ok {
		_spec.SetField(groupstatusstate.FieldStableStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseExcerpt(); ok {
		_spec.SetField(groupstatusstate.FieldResponseExcerpt, field.TypeString, value)
	}
	if _u.mutation.ResponseExcerptCleared() {
		_spec.ClearField(groupstatusstate.FieldResponseExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusstate.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(groupstatusstate.FieldLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(groupstatusstate.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusstate.FieldHTTPCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPCode(); ok {
		_spec.AddField(groupstatusstate.FieldHTTPCode, field.TypeInt, value)
	}
	if _u.mutation.HTTPCodeCleared() {
		_spec.ClearField(groupstatusstate.FieldHTTPCode, field.TypeInt)
	}
	if value, ok := _u.mutation.SubStatus(); ok {
		_spec.SetField(groupstatusstate.FieldSubStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusstate.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(groupstatusstate.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusstate.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.ObservedAtCleared() {
		_spec.ClearField(groupstatusstate.FieldObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsecutiveDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveDown(); ok {
		_spec.AddField(groupstatusstate.FieldConsecutiveDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveNonDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveNonDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveNonDown(); ok {
		_spec.AddField(groupstatusstate.FieldConsecutiveNonDown, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupstatusstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupStatusStateUpdateOne is the builder for updating a single GroupStatusState entity.
type GroupStatusStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupStatusStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupStatusStateUpdateOne) SetUpdatedAt(v time.Time) *GroupStatusStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupStatusStateUpdateOne) SetGroupID(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableGroupID(v *int64) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupStatusStateUpdateOne) AddGroupID(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *GroupStatusStateUpdateOne) SetConfigID(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.ResetConfigID()
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableConfigID(v *int64) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// AddConfigID adds value to the "config_id" field.
func (_u *GroupStatusStateUpdateOne) AddConfigID(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.AddConfigID(v)
	return _u
}

// SetLatestStatus sets the "latest_status" field.
func (_u *GroupStatusStateUpdateOne) SetLatestStatus(v string) *GroupStatusStateUpdateOne {
	_u.mutation.SetLatestStatus(v)
	return _u
}

// SetNillableLatestStatus sets the "latest_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableLatestStatus(v *string) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetLatestStatus(*v)
	}
	return _u
}

// SetStableStatus sets the "stable_status" field.
func (_u *GroupStatusStateUpdateOne) SetStableStatus(v string) *GroupStatusStateUpdateOne {
	_u.mutation.SetStableStatus(v)
	return _u
}

// SetNillableStableStatus sets the "stable_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableStableStatus(v *string) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetStableStatus(*v)
	}
	return _u
}

// SetResponseExcerpt sets the "response_excerpt" field.
func (_u *GroupStatusStateUpdateOne) SetResponseExcerpt(v string) *GroupStatusStateUpdateOne {
	_u.mutation.SetResponseExcerpt(v)
	return _u
}

// SetNillableResponseExcerpt sets the "response_excerpt" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableResponseExcerpt(v *string) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetResponseExcerpt(*v)
	}
	return _u
}

// ClearResponseExcerpt clears the value of the "response_excerpt" field.
func (_u *GroupStatusStateUpdateOne) ClearResponseExcerpt() *GroupStatusStateUpdateOne {
	_u.mutation.ClearResponseExcerpt()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GroupStatusStateUpdateOne) SetLatencyMs(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableLatencyMs(v *int64) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GroupStatusStateUpdateOne) AddLatencyMs(v int64) *GroupStatusStateUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *GroupStatusStateUpdateOne) ClearLatencyMs() *GroupStatusStateUpdateOne {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetHTTPCode sets the "http_code" field.
func (_u *GroupStatusStateUpdateOne) SetHTTPCode(v int) *GroupStatusStateUpdateOne {
	_u.mutation.ResetHTTPCode()
	_u.mutation.SetHTTPCode(v)
	return _u
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableHTTPCode(v *int) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetHTTPCode(*v)
	}
	return _u
}

// AddHTTPCode adds value to the "http_code" field.
func (_u *GroupStatusStateUpdateOne) AddHTTPCode(v int) *GroupStatusStateUpdateOne {
	_u.mutation.AddHTTPCode(v)
	return _u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (_u *GroupStatusStateUpdateOne) ClearHTTPCode() *GroupStatusStateUpdateOne {
	_u.mutation.ClearHTTPCode()
	return _u
}

// SetSubStatus sets the "sub_status" field.
func (_u *GroupStatusStateUpdateOne) SetSubStatus(v string) *GroupStatusStateUpdateOne {
	_u.mutation.SetSubStatus(v)
	return _u
}

// SetNillableSubStatus sets the "sub_status" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableSubStatus(v *string) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetSubStatus(*v)
	}
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *GroupStatusStateUpdateOne) SetErrorDetail(v string) *GroupStatusStateUpdateOne {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableErrorDetail(v *string) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *GroupStatusStateUpdateOne) ClearErrorDetail() *GroupStatusStateUpdateOne {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupStatusStateUpdateOne) SetObservedAt(v time.Time) *GroupStatusStateUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableObservedAt(v *time.Time) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// ClearObservedAt clears the value of the "observed_at" field.
func (_u *GroupStatusStateUpdateOne) ClearObservedAt() *GroupStatusStateUpdateOne {
	_u.mutation.ClearObservedAt()
	return _u
}

// SetConsecutiveDown sets the "consecutive_down" field.
func (_u *GroupStatusStateUpdateOne) SetConsecutiveDown(v int) *GroupStatusStateUpdateOne {
	_u.mutation.ResetConsecutiveDown()
	_u.mutation.SetConsecutiveDown(v)
	return _u
}

// SetNillableConsecutiveDown sets the "consecutive_down" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableConsecutiveDown(v *int) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetConsecutiveDown(*v)
	}
	return _u
}

// AddConsecutiveDown adds value to the "consecutive_down" field.
func (_u *GroupStatusStateUpdateOne) AddConsecutiveDown(v int) *GroupStatusStateUpdateOne {
	_u.mutation.AddConsecutiveDown(v)
	return _u
}

// SetConsecutiveNonDown sets the "consecutive_non_down" field.
func (_u *GroupStatusStateUpdateOne) SetConsecutiveNonDown(v int) *GroupStatusStateUpdateOne {
	_u.mutation.ResetConsecutiveNonDown()
	_u.mutation.SetConsecutiveNonDown(v)
	return _u
}

// SetNillableConsecutiveNonDown sets the "consecutive_non_down" field if the given value is not nil.
func (_u *GroupStatusStateUpdateOne) SetNillableConsecutiveNonDown(v *int) *GroupStatusStateUpdateOne {
	if v != nil {
		_u.SetConsecutiveNonDown(*v)
	}
	return _u
}

// AddConsecutiveNonDown adds value to the "consecutive_non_down" field.
func (_u *GroupStatusStateUpdateOne) AddConsecutiveNonDown(v int) *GroupStatusStateUpdateOne {
	_u.mutation.AddConsecutiveNonDown(v)
	return _u
}

// Mutation returns the GroupStatusStateMutation object of the builder.
func (_u *GroupStatusStateUpdateOne) Mutation() *GroupStatusStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupStatusStateUpdate builder.
func (_u *GroupStatusStateUpdateOne) Where(ps ...predicate.GroupStatusState) *GroupStatusStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupStatusStateUpdateOne) Select(field string, fields ...string) *GroupStatusStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupStatusState entity.
func (_u *GroupStatusStateUpdateOne) Save(ctx context.Context) (*GroupStatusState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupStatusStateUpdateOne) SaveX(ctx context.Context) *GroupStatusState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupStatusStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupStatusStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupStatusStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupstatusstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GroupStatusStateUpdateOne) sqlSave(ctx context.Context) (_node *GroupStatusState, err error) {
	_spec := sqlgraph.NewUpdateSpec(groupstatusstate.Table, groupstatusstate.Columns, sqlgraph.NewFieldSpec(groupstatusstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupStatusState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupstatusstate.FieldID)
		for _, f := range fields {
			if !groupstatusstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupstatusstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupstatusstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupstatusstate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupstatusstate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusstate.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigID(); ok {
		_spec.AddField(groupstatusstate.FieldConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LatestStatus(); ok {
		_spec.SetField(groupstatusstate.FieldLatestStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StableStatus(); ok {
		_spec.SetField(groupstatusstate.FieldStableStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseExcerpt(); ok {
		_spec.SetField(groupstatusstate.FieldResponseExcerpt, field.TypeString, value)
	}
	if _u.mutation.ResponseExcerptCleared() {
		_spec.ClearField(groupstatusstate.FieldResponseExcerpt, field.TypeString)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusstate.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(groupstatusstate.FieldLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(groupstatusstate.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusstate.FieldHTTPCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPCode(); ok {
		_spec.AddField(groupstatusstate.FieldHTTPCode, field.TypeInt, value)
	}
	if _u.mutation.HTTPCodeCleared() {
		_spec.ClearField(groupstatusstate.FieldHTTPCode, field.TypeInt)
	}
	if value, ok := _u.mutation.SubStatus(); ok {
		_spec.SetField(groupstatusstate.FieldSubStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusstate.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(groupstatusstate.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusstate.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.ObservedAtCleared() {
		_spec.ClearField(groupstatusstate.FieldObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsecutiveDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveDown(); ok {
		_spec.AddField(groupstatusstate.FieldConsecutiveDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveNonDown(); ok {
		_spec.SetField(groupstatusstate.FieldConsecutiveNonDown, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveNonDown(); ok {
		_spec.AddField(groupstatusstate.FieldConsecutiveNonDown, field.TypeInt, value)
	}
	_node = &GroupStatusState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupstatusstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
