// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusjuicerecord"
)

// GroupStatusJuiceRecordCreate is the builder for creating a GroupStatusJuiceRecord entity.
type GroupStatusJuiceRecordCreate struct {
	config
	mutation *GroupStatusJuiceRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupStatusJuiceRecordCreate) SetGroupID(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetConfigID sets the "config_id" field.
func (_c *GroupStatusJuiceRecordCreate) SetConfigID(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetConfigID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *GroupStatusJuiceRecordCreate) SetModel(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableModel(v *string) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetEffort sets the "effort" field.
func (_c *GroupStatusJuiceRecordCreate) SetEffort(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetEffort(v)
	return _c
}

// SetNillableEffort sets the "effort" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableEffort(v *string) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetEffort(*v)
	}
	return _c
}

// SetClassification sets the "classification" field.
func (_c *GroupStatusJuiceRecordCreate) SetClassification(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetClassification(v)
	return _c
}

// SetNormalizedValue sets the "normalized_value" field.
func (_c *GroupStatusJuiceRecordCreate) SetNormalizedValue(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetNormalizedValue(v)
	return _c
}

// SetNillableNormalizedValue sets the "normalized_value" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableNormalizedValue(v *string) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetNormalizedValue(*v)
	}
	return _c
}

// SetAnswerExcerpt sets the "answer_excerpt" field.
func (_c *GroupStatusJuiceRecordCreate) SetAnswerExcerpt(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetAnswerExcerpt(v)
	return _c
}

// SetNillableAnswerExcerpt sets the "answer_excerpt" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableAnswerExcerpt(v *string) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetAnswerExcerpt(*v)
	}
	return _c
}

// SetHTTPCode sets the "http_code" field.
func (_c *GroupStatusJuiceRecordCreate) SetHTTPCode(v int) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetHTTPCode(v)
	return _c
}

// SetNillableHTTPCode sets the "http_code" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableHTTPCode(v *int) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetHTTPCode(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *GroupStatusJuiceRecordCreate) SetLatencyMs(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableLatencyMs(v *int64) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *GroupStatusJuiceRecordCreate) SetInputTokens(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableInputTokens(v *int64) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *GroupStatusJuiceRecordCreate) SetOutputTokens(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableOutputTokens(v *int64) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_c *GroupStatusJuiceRecordCreate) SetReasoningTokens(v int64) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetReasoningTokens(v)
	return _c
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableReasoningTokens(v *int64) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetReasoningTokens(*v)
	}
	return _c
}

// SetErrorDetail sets the "error_detail" field.
func (_c *GroupStatusJuiceRecordCreate) SetErrorDetail(v string) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetErrorDetail(v)
	return _c
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableErrorDetail(v *string) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetErrorDetail(*v)
	}
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *GroupStatusJuiceRecordCreate) SetObservedAt(v time.Time) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupStatusJuiceRecordCreate) SetCreatedAt(v time.Time) *GroupStatusJuiceRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupStatusJuiceRecordCreate) SetNillableCreatedAt(v *time.Time) *GroupStatusJuiceRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the GroupStatusJuiceRecordMutation object of the builder.
func (_c *GroupStatusJuiceRecordCreate) Mutation() *GroupStatusJuiceRecordMutation {
	return _c.mutation
}

// Save creates the GroupStatusJuiceRecord in the database.
func (_c *GroupStatusJuiceRecordCreate) Save(ctx context.Context) (*GroupStatusJuiceRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupStatusJuiceRecordCreate) SaveX(ctx context.Context) *GroupStatusJuiceRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupStatusJuiceRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupStatusJuiceRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupStatusJuiceRecordCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := groupstatusjuicerecord.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Effort(); !ok {
		v := groupstatusjuicerecord.DefaultEffort
		_c.mutation.SetEffort(v)
	}
	if _, ok := _c.mutation.NormalizedValue(); !ok {
		v := groupstatusjuicerecord.DefaultNormalizedValue
		_c.mutation.SetNormalizedValue(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := groupstatusjuicerecord.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := groupstatusjuicerecord.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.ReasoningTokens(); !ok {
		v := groupstatusjuicerecord.DefaultReasoningTokens
		_c.mutation.SetReasoningTokens(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupstatusjuicerecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupStatusJuiceRecordCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.group_id"`)}
	}
	if _, ok := _c.mutation.ConfigID(); !ok {
		return &ValidationError{Name: "config_id", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.config_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.model"`)}
	}
	if _, ok := _c.mutation.Effort(); !ok {
		return &ValidationError{Name: "effort", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.effort"`)}
	}
	if _, ok := _c.mutation.Classification(); !ok {
		return &ValidationError{Name: "classification", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.classification"`)}
	}
	if _, ok := _c.mutation.NormalizedValue(); !ok {
		return &ValidationError{Name: "normalized_value", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.normalized_value"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.output_tokens"`)}
	}
	if _, ok := _c.mutation.ReasoningTokens(); !ok {
		return &ValidationError{Name: "reasoning_tokens", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.reasoning_tokens"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.observed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupStatusJuiceRecord.created_at"`)}
	}
	return nil
}

func (_c *GroupStatusJuiceRecordCreate) sqlSave(ctx context.Context) (*GroupStatusJuiceRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupStatusJuiceRecordCreate) createSpec() (*GroupStatusJuiceRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupStatusJuiceRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupstatusjuicerecord.Table, sqlgraph.NewFieldSpec(groupstatusjuicerecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.ConfigID(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldConfigID, field.TypeInt64, value)
		_node.ConfigID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Effort(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldEffort, field.TypeString, value)
		_node.Effort = value
	}
	if value, ok := _c.mutation.Classification(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldClassification, field.TypeString, value)
		_node.Classification = value
	}
	if value, ok := _c.mutation.NormalizedValue(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldNormalizedValue, field.TypeString, value)
		_node.NormalizedValue = value
	}
	if value, ok := _c.mutation.AnswerExcerpt(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldAnswerExcerpt, field.TypeString, value)
		_node.AnswerExcerpt = &value
	}
	if value, ok := _c.mutation.HTTPCode(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldHTTPCode, field.TypeInt, value)
		_node.HTTPCode = &value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.ReasoningTokens(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldReasoningTokens, field.TypeInt64, value)
		_node.ReasoningTokens = value
	}
	if value, ok := _c.mutation.ErrorDetail(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldErrorDetail, field.TypeString, value)
		_node.ErrorDetail = &value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupstatusjuicerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupStatusJuiceRecord.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupStatusJuiceRecordUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupStatusJuiceRecordCreate) OnConflict(opts ...sql.ConflictOption) *GroupStatusJuiceRecordUpsertOne {
	_c.conflict = opts
	return &GroupStatusJuiceRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupStatusJuiceRecordCreate) OnConflictColumns(columns ...string) *GroupStatusJuiceRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupStatusJuiceRecordUpsertOne{
		create: _c,
	}
}

type (
	// GroupStatusJuiceRecordUpsertOne is the builder for "upsert"-ing
	//  one GroupStatusJuiceRecord node.
	GroupStatusJuiceRecordUpsertOne struct {
		create *GroupStatusJuiceRecordCreate
	}

	// GroupStatusJuiceRecordUpsert is the "OnConflict" setter.
	GroupStatusJuiceRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupStatusJuiceRecordUpsert) SetGroupID(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateGroupID() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusJuiceRecordUpsert) AddGroupID(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldGroupID, v)
	return u
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusJuiceRecordUpsert) SetConfigID(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldConfigID, v)
	return u
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateConfigID() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldConfigID)
	return u
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusJuiceRecordUpsert) AddConfigID(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldConfigID, v)
	return u
}

// SetModel sets the "model" field.
func (u *GroupStatusJuiceRecordUpsert) SetModel(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateModel() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldModel)
	return u
}

// SetEffort sets the "effort" field.
func (u *GroupStatusJuiceRecordUpsert) SetEffort(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldEffort, v)
	return u
}

// UpdateEffort sets the "effort" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateEffort() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldEffort)
	return u
}

// SetClassification sets the "classification" field.
func (u *GroupStatusJuiceRecordUpsert) SetClassification(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldClassification, v)
	return u
}

// UpdateClassification sets the "classification" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateClassification() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldClassification)
	return u
}

// SetNormalizedValue sets the "normalized_value" field.
func (u *GroupStatusJuiceRecordUpsert) SetNormalizedValue(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldNormalizedValue, v)
	return u
}

// UpdateNormalizedValue sets the "normalized_value" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateNormalizedValue() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldNormalizedValue)
	return u
}

// SetAnswerExcerpt sets the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsert) SetAnswerExcerpt(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldAnswerExcerpt, v)
	return u
}

// UpdateAnswerExcerpt sets the "answer_excerpt" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateAnswerExcerpt() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldAnswerExcerpt)
	return u
}

// ClearAnswerExcerpt clears the value of the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsert) ClearAnswerExcerpt() *GroupStatusJuiceRecordUpsert {
	u.SetNull(groupstatusjuicerecord.FieldAnswerExcerpt)
	return u
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusJuiceRecordUpsert) SetHTTPCode(v int) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldHTTPCode, v)
	return u
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateHTTPCode() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldHTTPCode)
	return u
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusJuiceRecordUpsert) AddHTTPCode(v int) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldHTTPCode, v)
	return u
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusJuiceRecordUpsert) ClearHTTPCode() *GroupStatusJuiceRecordUpsert {
	u.SetNull(groupstatusjuicerecord.FieldHTTPCode)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsert) SetLatencyMs(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateLatencyMs() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsert) AddLatencyMs(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsert) ClearLatencyMs() *GroupStatusJuiceRecordUpsert {
	u.SetNull(groupstatusjuicerecord.FieldLatencyMs)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) SetInputTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateInputTokens() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) AddInputTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) SetOutputTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateOutputTokens() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) AddOutputTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldOutputTokens, v)
	return u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) SetReasoningTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldReasoningTokens, v)
	return u
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateReasoningTokens() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldReasoningTokens)
	return u
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsert) AddReasoningTokens(v int64) *GroupStatusJuiceRecordUpsert {
	u.Add(groupstatusjuicerecord.FieldReasoningTokens, v)
	return u
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsert) SetErrorDetail(v string) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldErrorDetail, v)
	return u
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateErrorDetail() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldErrorDetail)
	return u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsert) ClearErrorDetail() *GroupStatusJuiceRecordUpsert {
	u.SetNull(groupstatusjuicerecord.FieldErrorDetail)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusJuiceRecordUpsert) SetObservedAt(v time.Time) *GroupStatusJuiceRecordUpsert {
	u.Set(groupstatusjuicerecord.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsert) UpdateObservedAt() *GroupStatusJuiceRecordUpsert {
	u.SetExcluded(groupstatusjuicerecord.FieldObservedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupStatusJuiceRecordUpsertOne) UpdateNewValues() *GroupStatusJuiceRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupstatusjuicerecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupStatusJuiceRecordUpsertOne) Ignore() *GroupStatusJuiceRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupStatusJuiceRecordUpsertOne) DoNothing() *GroupStatusJuiceRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupStatusJuiceRecordCreate.OnConflict
// documentation for more info.
func (u *GroupStatusJuiceRecordUpsertOne) Update(set func(*GroupStatusJuiceRecordUpsert)) *GroupStatusJuiceRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupStatusJuiceRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetGroupID(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddGroupID(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateGroupID() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateGroupID()
	})
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetConfigID(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetConfigID(v)
	})
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddConfigID(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateConfigID() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateConfigID()
	})
}

// SetModel sets the "model" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetModel(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateModel() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateModel()
	})
}

// SetEffort sets the "effort" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetEffort(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetEffort(v)
	})
}

// UpdateEffort sets the "effort" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateEffort() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateEffort()
	})
}

// SetClassification sets the "classification" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetClassification(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetClassification(v)
	})
}

// UpdateClassification sets the "classification" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateClassification() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateClassification()
	})
}

// SetNormalizedValue sets the "normalized_value" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetNormalizedValue(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetNormalizedValue(v)
	})
}

// UpdateNormalizedValue sets the "normalized_value" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateNormalizedValue() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateNormalizedValue()
	})
}

// SetAnswerExcerpt sets the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetAnswerExcerpt(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetAnswerExcerpt(v)
	})
}

// UpdateAnswerExcerpt sets the "answer_excerpt" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateAnswerExcerpt() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateAnswerExcerpt()
	})
}

// ClearAnswerExcerpt clears the value of the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsertOne) ClearAnswerExcerpt() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearAnswerExcerpt()
	})
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetHTTPCode(v int) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetHTTPCode(v)
	})
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddHTTPCode(v int) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddHTTPCode(v)
	})
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateHTTPCode() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateHTTPCode()
	})
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertOne) ClearHTTPCode() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearHTTPCode()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetLatencyMs(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddLatencyMs(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateLatencyMs() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertOne) ClearLatencyMs() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearLatencyMs()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetInputTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddInputTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateInputTokens() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetOutputTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddOutputTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateOutputTokens() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetReasoningTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetReasoningTokens(v)
	})
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsertOne) AddReasoningTokens(v int64) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddReasoningTokens(v)
	})
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateReasoningTokens() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateReasoningTokens()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetErrorDetail(v string) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateErrorDetail() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsertOne) ClearErrorDetail() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearErrorDetail()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusJuiceRecordUpsertOne) SetObservedAt(v time.Time) *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertOne) UpdateObservedAt() *GroupStatusJuiceRecordUpsertOne {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *GroupStatusJuiceRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupStatusJuiceRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupStatusJuiceRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupStatusJuiceRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupStatusJuiceRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupStatusJuiceRecordCreateBulk is the builder for creating many GroupStatusJuiceRecord entities in bulk.
type GroupStatusJuiceRecordCreateBulk struct {
	config
	err      error
	builders []*GroupStatusJuiceRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupStatusJuiceRecord entities in the database.
func (_c *GroupStatusJuiceRecordCreateBulk) Save(ctx context.Context) ([]*GroupStatusJuiceRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupStatusJuiceRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupStatusJuiceRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupStatusJuiceRecordCreateBulk) SaveX(ctx context.Context) []*GroupStatusJuiceRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupStatusJuiceRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupStatusJuiceRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupStatusJuiceRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupStatusJuiceRecordUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupStatusJuiceRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupStatusJuiceRecordUpsertBulk {
	_c.conflict = opts
	return &GroupStatusJuiceRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupStatusJuiceRecordCreateBulk) OnConflictColumns(columns ...string) *GroupStatusJuiceRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupStatusJuiceRecordUpsertBulk{
		create: _c,
	}
}

// GroupStatusJuiceRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupStatusJuiceRecord nodes.
type GroupStatusJuiceRecordUpsertBulk struct {
	create *GroupStatusJuiceRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateNewValues() *GroupStatusJuiceRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupstatusjuicerecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupStatusJuiceRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupStatusJuiceRecordUpsertBulk) Ignore() *GroupStatusJuiceRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupStatusJuiceRecordUpsertBulk) DoNothing() *GroupStatusJuiceRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupStatusJuiceRecordCreateBulk.OnConflict
// documentation for more info.
func (u *GroupStatusJuiceRecordUpsertBulk) Update(set func(*GroupStatusJuiceRecordUpsert)) *GroupStatusJuiceRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupStatusJuiceRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetGroupID(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddGroupID(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateGroupID() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateGroupID()
	})
}

// SetConfigID sets the "config_id" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetConfigID(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetConfigID(v)
	})
}

// AddConfigID adds v to the "config_id" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddConfigID(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddConfigID(v)
	})
}

// UpdateConfigID sets the "config_id" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateConfigID() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateConfigID()
	})
}

// SetModel sets the "model" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetModel(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateModel() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateModel()
	})
}

// SetEffort sets the "effort" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetEffort(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetEffort(v)
	})
}

// UpdateEffort sets the "effort" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateEffort() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateEffort()
	})
}

// SetClassification sets the "classification" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetClassification(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetClassification(v)
	})
}

// UpdateClassification sets the "classification" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateClassification() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateClassification()
	})
}

// SetNormalizedValue sets the "normalized_value" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetNormalizedValue(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetNormalizedValue(v)
	})
}

// UpdateNormalizedValue sets the "normalized_value" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateNormalizedValue() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateNormalizedValue()
	})
}

// SetAnswerExcerpt sets the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetAnswerExcerpt(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetAnswerExcerpt(v)
	})
}

// UpdateAnswerExcerpt sets the "answer_excerpt" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateAnswerExcerpt() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateAnswerExcerpt()
	})
}

// ClearAnswerExcerpt clears the value of the "answer_excerpt" field.
func (u *GroupStatusJuiceRecordUpsertBulk) ClearAnswerExcerpt() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearAnswerExcerpt()
	})
}

// SetHTTPCode sets the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetHTTPCode(v int) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetHTTPCode(v)
	})
}

// AddHTTPCode adds v to the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddHTTPCode(v int) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddHTTPCode(v)
	})
}

// UpdateHTTPCode sets the "http_code" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateHTTPCode() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateHTTPCode()
	})
}

// ClearHTTPCode clears the value of the "http_code" field.
func (u *GroupStatusJuiceRecordUpsertBulk) ClearHTTPCode() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearHTTPCode()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetLatencyMs(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddLatencyMs(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateLatencyMs() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GroupStatusJuiceRecordUpsertBulk) ClearLatencyMs() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearLatencyMs()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetInputTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddInputTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateInputTokens() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetOutputTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddOutputTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateOutputTokens() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetReasoningTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetReasoningTokens(v)
	})
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *GroupStatusJuiceRecordUpsertBulk) AddReasoningTokens(v int64) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.AddReasoningTokens(v)
	})
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateReasoningTokens() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateReasoningTokens()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetErrorDetail(v string) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateErrorDetail() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *GroupStatusJuiceRecordUpsertBulk) ClearErrorDetail() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.ClearErrorDetail()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupStatusJuiceRecordUpsertBulk) SetObservedAt(v time.Time) *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupStatusJuiceRecordUpsertBulk) UpdateObservedAt() *GroupStatusJuiceRecordUpsertBulk {
	return u.Update(func(s *GroupStatusJuiceRecordUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *GroupStatusJuiceRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupStatusJuiceRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupStatusJuiceRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupStatusJuiceRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
