// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupstatusmodeltracerun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupStatusModelTraceRunDelete is the builder for deleting a GroupStatusModelTraceRun entity.
type GroupStatusModelTraceRunDelete struct {
	config
	hooks    []Hook
	mutation *GroupStatusModelTraceRunMutation
}

// Where appends a list predicates to the GroupStatusModelTraceRunDelete builder.
func (_d *GroupStatusModelTraceRunDelete) Where(ps ...predicate.GroupStatusModelTraceRun) *GroupStatusModelTraceRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupStatusModelTraceRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusModelTraceRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupStatusModelTraceRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupstatusmodeltracerun.Table, sqlgraph.NewFieldSpec(groupstatusmodeltracerun.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupStatusModelTraceRunDeleteOne is the builder for deleting a single GroupStatusModelTraceRun entity.
type GroupStatusModelTraceRunDeleteOne struct {
	_d *GroupStatusModelTraceRunDelete
}

// Where appends a list predicates to the GroupStatusModelTraceRunDelete builder.
func (_d *GroupStatusModelTraceRunDeleteOne) Where(ps ...predicate.GroupStatusModelTraceRun) *GroupStatusModelTraceRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupStatusModelTraceRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupstatusmodeltracerun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupStatusModelTraceRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
