// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/personaltoken"
)

// PersonalToken is the model entity for the PersonalToken schema.
type PersonalToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// TokenHint holds the value of the "token_hint" field.
	TokenHint string `json:"token_hint,omitempty"`
	// UserTokenVersion holds the value of the "user_token_version" field.
	UserTokenVersion int64 `json:"user_token_version,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// LastUsedIP holds the value of the "last_used_ip" field.
	LastUsedIP string `json:"last_used_ip,omitempty"`
	// CreatedIP holds the value of the "created_ip" field.
	CreatedIP string `json:"created_ip,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PersonalToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case personaltoken.FieldID, personaltoken.FieldUserID, personaltoken.FieldUserTokenVersion:
			values[i] = new(sql.NullInt64)
		case personaltoken.FieldTokenHash, personaltoken.FieldTokenHint, personaltoken.FieldLastUsedIP, personaltoken.FieldCreatedIP:
			values[i] = new(sql.NullString)
		case personaltoken.FieldExpiresAt, personaltoken.FieldLastUsedAt, personaltoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PersonalToken fields.
func (_m *PersonalToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case personaltoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case personaltoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case personaltoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case personaltoken.FieldTokenHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hint", values[i])
			} else if value.Valid {
				_m.TokenHint = value.String
			}
		case personaltoken.FieldUserTokenVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_token_version", values[i])
			} else if value.Valid {
				_m.UserTokenVersion = value.Int64
			}
		case personaltoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case personaltoken.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case personaltoken.FieldLastUsedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_ip", values[i])
			} else if value.Valid {
				_m.LastUsedIP = value.String
			}
		case personaltoken.FieldCreatedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_ip", values[i])
			} else if value.Valid {
				_m.CreatedIP = value.String
			}
		case personaltoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PersonalToken.
// This includes values selected through modifiers, order, etc.
func (_m *PersonalToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PersonalToken.
// Note that you need to call PersonalToken.Unwrap() before calling this method if this PersonalToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PersonalToken) Update() *PersonalTokenUpdateOne {
	return NewPersonalTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PersonalToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PersonalToken) Unwrap() *PersonalToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PersonalToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PersonalToken) String() string {
	var builder strings.Builder
	builder.WriteString("PersonalToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("token_hint=")
	builder.WriteString(_m.TokenHint)
	builder.WriteString(", ")
	builder.WriteString("user_token_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserTokenVersion))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_used_ip=")
	builder.WriteString(_m.LastUsedIP)
	builder.WriteString(", ")
	builder.WriteString("created_ip=")
	builder.WriteString(_m.CreatedIP)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PersonalTokens is a parsable slice of PersonalToken.
type PersonalTokens []*PersonalToken
