// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdate) SetUserID(v int64) *SupportTicketUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SupportTicketUpdate) AddUserID(v int64) *SupportTicketUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *SupportTicketUpdate) SetUserEmail(v string) *SupportTicketUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserEmail(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdate) SetTitle(v string) *SupportTicketUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableTitle(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdate) SetCategory(v string) *SupportTicketUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableCategory(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v string) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserUnread sets the "user_unread" field.
func (_u *SupportTicketUpdate) SetUserUnread(v bool) *SupportTicketUpdate {
	_u.mutation.SetUserUnread(v)
	return _u
}

// SetNillableUserUnread sets the "user_unread" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserUnread(v *bool) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserUnread(*v)
	}
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *SupportTicketUpdate) SetMessageCount(v int) *SupportTicketUpdate {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableMessageCount(v *int) *SupportTicketUpdate {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *SupportTicketUpdate) AddMessageCount(v int) *SupportTicketUpdate {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdate) SetLastMessageAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdate) SetClosedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdate) ClearClosedAt() *SupportTicketUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetClosedByUserID sets the "closed_by_user_id" field.
func (_u *SupportTicketUpdate) SetClosedByUserID(v int64) *SupportTicketUpdate {
	_u.mutation.ResetClosedByUserID()
	_u.mutation.SetClosedByUserID(v)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedByUserID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedByUserID(*v)
	}
	return _u
}

// AddClosedByUserID adds value to the "closed_by_user_id" field.
func (_u *SupportTicketUpdate) AddClosedByUserID(v int64) *SupportTicketUpdate {
	_u.mutation.AddClosedByUserID(v)
	return _u
}

// ClearClosedByUserID clears the value of the "closed_by_user_id" field.
func (_u *SupportTicketUpdate) ClearClosedByUserID() *SupportTicketUpdate {
	_u.mutation.ClearClosedByUserID()
	return _u
}

// SetClosedByRole sets the "closed_by_role" field.
func (_u *SupportTicketUpdate) SetClosedByRole(v string) *SupportTicketUpdate {
	_u.mutation.SetClosedByRole(v)
	return _u
}

// SetNillableClosedByRole sets the "closed_by_role" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedByRole(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedByRole(*v)
	}
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := supportticket.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClosedByRole(); ok {
		if err := supportticket.ClosedByRoleValidator(v); err != nil {
			return &ValidationError{Name: "closed_by_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.closed_by_role": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(supportticket.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserUnread(); ok {
		_spec.SetField(supportticket.FieldUserUnread, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(supportticket.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(supportticket.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedByUserID(); ok {
		_spec.SetField(supportticket.FieldClosedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedByUserID(); ok {
		_spec.AddField(supportticket.FieldClosedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ClosedByUserIDCleared() {
		_spec.ClearField(supportticket.FieldClosedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedByRole(); ok {
		_spec.SetField(supportticket.FieldClosedByRole, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdateOne) SetUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SupportTicketUpdateOne) AddUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *SupportTicketUpdateOne) SetUserEmail(v string) *SupportTicketUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserEmail(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdateOne) SetTitle(v string) *SupportTicketUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableTitle(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdateOne) SetCategory(v string) *SupportTicketUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableCategory(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v string) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserUnread sets the "user_unread" field.
func (_u *SupportTicketUpdateOne) SetUserUnread(v bool) *SupportTicketUpdateOne {
	_u.mutation.SetUserUnread(v)
	return _u
}

// SetNillableUserUnread sets the "user_unread" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserUnread(v *bool) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserUnread(*v)
	}
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *SupportTicketUpdateOne) SetMessageCount(v int) *SupportTicketUpdateOne {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableMessageCount(v *int) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *SupportTicketUpdateOne) AddMessageCount(v int) *SupportTicketUpdateOne {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdateOne) SetLastMessageAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdateOne) SetClosedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdateOne) ClearClosedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetClosedByUserID sets the "closed_by_user_id" field.
func (_u *SupportTicketUpdateOne) SetClosedByUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.ResetClosedByUserID()
	_u.mutation.SetClosedByUserID(v)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedByUserID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedByUserID(*v)
	}
	return _u
}

// AddClosedByUserID adds value to the "closed_by_user_id" field.
func (_u *SupportTicketUpdateOne) AddClosedByUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.AddClosedByUserID(v)
	return _u
}

// ClearClosedByUserID clears the value of the "closed_by_user_id" field.
func (_u *SupportTicketUpdateOne) ClearClosedByUserID() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedByUserID()
	return _u
}

// SetClosedByRole sets the "closed_by_role" field.
func (_u *SupportTicketUpdateOne) SetClosedByRole(v string) *SupportTicketUpdateOne {
	_u.mutation.SetClosedByRole(v)
	return _u
}

// SetNillableClosedByRole sets the "closed_by_role" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedByRole(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedByRole(*v)
	}
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := supportticket.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClosedByRole(); ok {
		if err := supportticket.ClosedByRoleValidator(v); err != nil {
			return &ValidationError{Name: "closed_by_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.closed_by_role": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(supportticket.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserUnread(); ok {
		_spec.SetField(supportticket.FieldUserUnread, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(supportticket.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(supportticket.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedByUserID(); ok {
		_spec.SetField(supportticket.FieldClosedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedByUserID(); ok {
		_spec.AddField(supportticket.FieldClosedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ClosedByUserIDCleared() {
		_spec.ClearField(supportticket.FieldClosedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedByRole(); ok {
		_spec.SetField(supportticket.FieldClosedByRole, field.TypeString, value)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
