// Code generated by ent, DO NOT EDIT.

package groupstatusstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldGroupID, v))
}

// ConfigID applies equality check predicate on the "config_id" field. It's identical to ConfigIDEQ.
func ConfigID(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConfigID, v))
}

// LatestStatus applies equality check predicate on the "latest_status" field. It's identical to LatestStatusEQ.
func LatestStatus(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldLatestStatus, v))
}

// StableStatus applies equality check predicate on the "stable_status" field. It's identical to StableStatusEQ.
func StableStatus(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldStableStatus, v))
}

// ResponseExcerpt applies equality check predicate on the "response_excerpt" field. It's identical to ResponseExcerptEQ.
func ResponseExcerpt(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldResponseExcerpt, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldLatencyMs, v))
}

// HTTPCode applies equality check predicate on the "http_code" field. It's identical to HTTPCodeEQ.
func HTTPCode(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldHTTPCode, v))
}

// SubStatus applies equality check predicate on the "sub_status" field. It's identical to SubStatusEQ.
func SubStatus(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldSubStatus, v))
}

// ErrorDetail applies equality check predicate on the "error_detail" field. It's identical to ErrorDetailEQ.
func ErrorDetail(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldErrorDetail, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldObservedAt, v))
}

// ConsecutiveDown applies equality check predicate on the "consecutive_down" field. It's identical to ConsecutiveDownEQ.
func ConsecutiveDown(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConsecutiveDown, v))
}

// ConsecutiveNonDown applies equality check predicate on the "consecutive_non_down" field. It's identical to ConsecutiveNonDownEQ.
func ConsecutiveNonDown(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConsecutiveNonDown, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldGroupID, v))
}

// ConfigIDEQ applies the EQ predicate on the "config_id" field.
func ConfigIDEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConfigID, v))
}

// ConfigIDNEQ applies the NEQ predicate on the "config_id" field.
func ConfigIDNEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldConfigID, v))
}

// ConfigIDIn applies the In predicate on the "config_id" field.
func ConfigIDIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldConfigID, vs...))
}

// ConfigIDNotIn applies the NotIn predicate on the "config_id" field.
func ConfigIDNotIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldConfigID, vs...))
}

// ConfigIDGT applies the GT predicate on the "config_id" field.
func ConfigIDGT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldConfigID, v))
}

// ConfigIDGTE applies the GTE predicate on the "config_id" field.
func ConfigIDGTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldConfigID, v))
}

// ConfigIDLT applies the LT predicate on the "config_id" field.
func ConfigIDLT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldConfigID, v))
}

// ConfigIDLTE applies the LTE predicate on the "config_id" field.
func ConfigIDLTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldConfigID, v))
}

// LatestStatusEQ applies the EQ predicate on the "latest_status" field.
func LatestStatusEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldLatestStatus, v))
}

// LatestStatusNEQ applies the NEQ predicate on the "latest_status" field.
func LatestStatusNEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldLatestStatus, v))
}

// LatestStatusIn applies the In predicate on the "latest_status" field.
func LatestStatusIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldLatestStatus, vs...))
}

// LatestStatusNotIn applies the NotIn predicate on the "latest_status" field.
func LatestStatusNotIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldLatestStatus, vs...))
}

// LatestStatusGT applies the GT predicate on the "latest_status" field.
func LatestStatusGT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldLatestStatus, v))
}

// LatestStatusGTE applies the GTE predicate on the "latest_status" field.
func LatestStatusGTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldLatestStatus, v))
}

// LatestStatusLT applies the LT predicate on the "latest_status" field.
func LatestStatusLT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldLatestStatus, v))
}

// LatestStatusLTE applies the LTE predicate on the "latest_status" field.
func LatestStatusLTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldLatestStatus, v))
}

// LatestStatusContains applies the Contains predicate on the "latest_status" field.
func LatestStatusContains(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContains(FieldLatestStatus, v))
}

// LatestStatusHasPrefix applies the HasPrefix predicate on the "latest_status" field.
func LatestStatusHasPrefix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasPrefix(FieldLatestStatus, v))
}

// LatestStatusHasSuffix applies the HasSuffix predicate on the "latest_status" field.
func LatestStatusHasSuffix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasSuffix(FieldLatestStatus, v))
}

// LatestStatusEqualFold applies the EqualFold predicate on the "latest_status" field.
func LatestStatusEqualFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEqualFold(FieldLatestStatus, v))
}

// LatestStatusContainsFold applies the ContainsFold predicate on the "latest_status" field.
func LatestStatusContainsFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContainsFold(FieldLatestStatus, v))
}

// StableStatusEQ applies the EQ predicate on the "stable_status" field.
func StableStatusEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldStableStatus, v))
}

// StableStatusNEQ applies the NEQ predicate on the "stable_status" field.
func StableStatusNEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldStableStatus, v))
}

// StableStatusIn applies the In predicate on the "stable_status" field.
func StableStatusIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldStableStatus, vs...))
}

// StableStatusNotIn applies the NotIn predicate on the "stable_status" field.
func StableStatusNotIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldStableStatus, vs...))
}

// StableStatusGT applies the GT predicate on the "stable_status" field.
func StableStatusGT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldStableStatus, v))
}

// StableStatusGTE applies the GTE predicate on the "stable_status" field.
func StableStatusGTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldStableStatus, v))
}

// StableStatusLT applies the LT predicate on the "stable_status" field.
func StableStatusLT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldStableStatus, v))
}

// StableStatusLTE applies the LTE predicate on the "stable_status" field.
func StableStatusLTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldStableStatus, v))
}

// StableStatusContains applies the Contains predicate on the "stable_status" field.
func StableStatusContains(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContains(FieldStableStatus, v))
}

// StableStatusHasPrefix applies the HasPrefix predicate on the "stable_status" field.
func StableStatusHasPrefix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasPrefix(FieldStableStatus, v))
}

// StableStatusHasSuffix applies the HasSuffix predicate on the "stable_status" field.
func StableStatusHasSuffix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasSuffix(FieldStableStatus, v))
}

// StableStatusEqualFold applies the EqualFold predicate on the "stable_status" field.
func StableStatusEqualFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEqualFold(FieldStableStatus, v))
}

// StableStatusContainsFold applies the ContainsFold predicate on the "stable_status" field.
func StableStatusContainsFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContainsFold(FieldStableStatus, v))
}

// ResponseExcerptEQ applies the EQ predicate on the "response_excerpt" field.
func ResponseExcerptEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldResponseExcerpt, v))
}

// ResponseExcerptNEQ applies the NEQ predicate on the "response_excerpt" field.
func ResponseExcerptNEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldResponseExcerpt, v))
}

// ResponseExcerptIn applies the In predicate on the "response_excerpt" field.
func ResponseExcerptIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldResponseExcerpt, vs...))
}

// ResponseExcerptNotIn applies the NotIn predicate on the "response_excerpt" field.
func ResponseExcerptNotIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldResponseExcerpt, vs...))
}

// ResponseExcerptGT applies the GT predicate on the "response_excerpt" field.
func ResponseExcerptGT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldResponseExcerpt, v))
}

// ResponseExcerptGTE applies the GTE predicate on the "response_excerpt" field.
func ResponseExcerptGTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldResponseExcerpt, v))
}

// ResponseExcerptLT applies the LT predicate on the "response_excerpt" field.
func ResponseExcerptLT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldResponseExcerpt, v))
}

// ResponseExcerptLTE applies the LTE predicate on the "response_excerpt" field.
func ResponseExcerptLTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldResponseExcerpt, v))
}

// ResponseExcerptContains applies the Contains predicate on the "response_excerpt" field.
func ResponseExcerptContains(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContains(FieldResponseExcerpt, v))
}

// ResponseExcerptHasPrefix applies the HasPrefix predicate on the "response_excerpt" field.
func ResponseExcerptHasPrefix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasPrefix(FieldResponseExcerpt, v))
}

// ResponseExcerptHasSuffix applies the HasSuffix predicate on the "response_excerpt" field.
func ResponseExcerptHasSuffix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasSuffix(FieldResponseExcerpt, v))
}

// ResponseExcerptIsNil applies the IsNil predicate on the "response_excerpt" field.
func ResponseExcerptIsNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIsNull(FieldResponseExcerpt))
}

// ResponseExcerptNotNil applies the NotNil predicate on the "response_excerpt" field.
func ResponseExcerptNotNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotNull(FieldResponseExcerpt))
}

// ResponseExcerptEqualFold applies the EqualFold predicate on the "response_excerpt" field.
func ResponseExcerptEqualFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEqualFold(FieldResponseExcerpt, v))
}

// ResponseExcerptContainsFold applies the ContainsFold predicate on the "response_excerpt" field.
func ResponseExcerptContainsFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContainsFold(FieldResponseExcerpt, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotNull(FieldLatencyMs))
}

// HTTPCodeEQ applies the EQ predicate on the "http_code" field.
func HTTPCodeEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldHTTPCode, v))
}

// HTTPCodeNEQ applies the NEQ predicate on the "http_code" field.
func HTTPCodeNEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldHTTPCode, v))
}

// HTTPCodeIn applies the In predicate on the "http_code" field.
func HTTPCodeIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldHTTPCode, vs...))
}

// HTTPCodeNotIn applies the NotIn predicate on the "http_code" field.
func HTTPCodeNotIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldHTTPCode, vs...))
}

// HTTPCodeGT applies the GT predicate on the "http_code" field.
func HTTPCodeGT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldHTTPCode, v))
}

// HTTPCodeGTE applies the GTE predicate on the "http_code" field.
func HTTPCodeGTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldHTTPCode, v))
}

// HTTPCodeLT applies the LT predicate on the "http_code" field.
func HTTPCodeLT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldHTTPCode, v))
}

// HTTPCodeLTE applies the LTE predicate on the "http_code" field.
func HTTPCodeLTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldHTTPCode, v))
}

// HTTPCodeIsNil applies the IsNil predicate on the "http_code" field.
func HTTPCodeIsNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIsNull(FieldHTTPCode))
}

// HTTPCodeNotNil applies the NotNil predicate on the "http_code" field.
func HTTPCodeNotNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotNull(FieldHTTPCode))
}

// SubStatusEQ applies the EQ predicate on the "sub_status" field.
func SubStatusEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldSubStatus, v))
}

// SubStatusNEQ applies the NEQ predicate on the "sub_status" field.
func SubStatusNEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldSubStatus, v))
}

// SubStatusIn applies the In predicate on the "sub_status" field.
func SubStatusIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldSubStatus, vs...))
}

// SubStatusNotIn applies the NotIn predicate on the "sub_status" field.
func SubStatusNotIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldSubStatus, vs...))
}

// SubStatusGT applies the GT predicate on the "sub_status" field.
func SubStatusGT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldSubStatus, v))
}

// SubStatusGTE applies the GTE predicate on the "sub_status" field.
func SubStatusGTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldSubStatus, v))
}

// SubStatusLT applies the LT predicate on the "sub_status" field.
func SubStatusLT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldSubStatus, v))
}

// SubStatusLTE applies the LTE predicate on the "sub_status" field.
func SubStatusLTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldSubStatus, v))
}

// SubStatusContains applies the Contains predicate on the "sub_status" field.
func SubStatusContains(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContains(FieldSubStatus, v))
}

// SubStatusHasPrefix applies the HasPrefix predicate on the "sub_status" field.
func SubStatusHasPrefix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasPrefix(FieldSubStatus, v))
}

// SubStatusHasSuffix applies the HasSuffix predicate on the "sub_status" field.
func SubStatusHasSuffix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasSuffix(FieldSubStatus, v))
}

// SubStatusEqualFold applies the EqualFold predicate on the "sub_status" field.
func SubStatusEqualFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEqualFold(FieldSubStatus, v))
}

// SubStatusContainsFold applies the ContainsFold predicate on the "sub_status" field.
func SubStatusContainsFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContainsFold(FieldSubStatus, v))
}

// ErrorDetailEQ applies the EQ predicate on the "error_detail" field.
func ErrorDetailEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldErrorDetail, v))
}

// ErrorDetailNEQ applies the NEQ predicate on the "error_detail" field.
func ErrorDetailNEQ(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldErrorDetail, v))
}

// ErrorDetailIn applies the In predicate on the "error_detail" field.
func ErrorDetailIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldErrorDetail, vs...))
}

// ErrorDetailNotIn applies the NotIn predicate on the "error_detail" field.
func ErrorDetailNotIn(vs ...string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldErrorDetail, vs...))
}

// ErrorDetailGT applies the GT predicate on the "error_detail" field.
func ErrorDetailGT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldErrorDetail, v))
}

// ErrorDetailGTE applies the GTE predicate on the "error_detail" field.
func ErrorDetailGTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldErrorDetail, v))
}

// ErrorDetailLT applies the LT predicate on the "error_detail" field.
func ErrorDetailLT(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldErrorDetail, v))
}

// ErrorDetailLTE applies the LTE predicate on the "error_detail" field.
func ErrorDetailLTE(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldErrorDetail, v))
}

// ErrorDetailContains applies the Contains predicate on the "error_detail" field.
func ErrorDetailContains(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContains(FieldErrorDetail, v))
}

// ErrorDetailHasPrefix applies the HasPrefix predicate on the "error_detail" field.
func ErrorDetailHasPrefix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasPrefix(FieldErrorDetail, v))
}

// ErrorDetailHasSuffix applies the HasSuffix predicate on the "error_detail" field.
func ErrorDetailHasSuffix(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldHasSuffix(FieldErrorDetail, v))
}

// ErrorDetailIsNil applies the IsNil predicate on the "error_detail" field.
func ErrorDetailIsNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIsNull(FieldErrorDetail))
}

// ErrorDetailNotNil applies the NotNil predicate on the "error_detail" field.
func ErrorDetailNotNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotNull(FieldErrorDetail))
}

// ErrorDetailEqualFold applies the EqualFold predicate on the "error_detail" field.
func ErrorDetailEqualFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEqualFold(FieldErrorDetail, v))
}

// ErrorDetailContainsFold applies the ContainsFold predicate on the "error_detail" field.
func ErrorDetailContainsFold(v string) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldContainsFold(FieldErrorDetail, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldObservedAt, v))
}

// ObservedAtIsNil applies the IsNil predicate on the "observed_at" field.
func ObservedAtIsNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIsNull(FieldObservedAt))
}

// ObservedAtNotNil applies the NotNil predicate on the "observed_at" field.
func ObservedAtNotNil() predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotNull(FieldObservedAt))
}

// ConsecutiveDownEQ applies the EQ predicate on the "consecutive_down" field.
func ConsecutiveDownEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConsecutiveDown, v))
}

// ConsecutiveDownNEQ applies the NEQ predicate on the "consecutive_down" field.
func ConsecutiveDownNEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldConsecutiveDown, v))
}

// ConsecutiveDownIn applies the In predicate on the "consecutive_down" field.
func ConsecutiveDownIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldConsecutiveDown, vs...))
}

// ConsecutiveDownNotIn applies the NotIn predicate on the "consecutive_down" field.
func ConsecutiveDownNotIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldConsecutiveDown, vs...))
}

// ConsecutiveDownGT applies the GT predicate on the "consecutive_down" field.
func ConsecutiveDownGT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldConsecutiveDown, v))
}

// ConsecutiveDownGTE applies the GTE predicate on the "consecutive_down" field.
func ConsecutiveDownGTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldConsecutiveDown, v))
}

// ConsecutiveDownLT applies the LT predicate on the "consecutive_down" field.
func ConsecutiveDownLT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldConsecutiveDown, v))
}

// ConsecutiveDownLTE applies the LTE predicate on the "consecutive_down" field.
func ConsecutiveDownLTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldConsecutiveDown, v))
}

// ConsecutiveNonDownEQ applies the EQ predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldEQ(FieldConsecutiveNonDown, v))
}

// ConsecutiveNonDownNEQ applies the NEQ predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownNEQ(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNEQ(FieldConsecutiveNonDown, v))
}

// ConsecutiveNonDownIn applies the In predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldIn(FieldConsecutiveNonDown, vs...))
}

// ConsecutiveNonDownNotIn applies the NotIn predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownNotIn(vs ...int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldNotIn(FieldConsecutiveNonDown, vs...))
}

// ConsecutiveNonDownGT applies the GT predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownGT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGT(FieldConsecutiveNonDown, v))
}

// ConsecutiveNonDownGTE applies the GTE predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownGTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldGTE(FieldConsecutiveNonDown, v))
}

// ConsecutiveNonDownLT applies the LT predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownLT(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLT(FieldConsecutiveNonDown, v))
}

// ConsecutiveNonDownLTE applies the LTE predicate on the "consecutive_non_down" field.
func ConsecutiveNonDownLTE(v int) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.FieldLTE(FieldConsecutiveNonDown, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupStatusState) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupStatusState) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupStatusState) predicate.GroupStatusState {
	return predicate.GroupStatusState(sql.NotPredicates(p))
}
