// Code generated by ent, DO NOT EDIT.

package groupstatusconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldEnabled, v))
}

// ProbeModel applies equality check predicate on the "probe_model" field. It's identical to ProbeModelEQ.
func ProbeModel(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldProbeModel, v))
}

// ProbePrompt applies equality check predicate on the "probe_prompt" field. It's identical to ProbePromptEQ.
func ProbePrompt(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldProbePrompt, v))
}

// ValidationMode applies equality check predicate on the "validation_mode" field. It's identical to ValidationModeEQ.
func ValidationMode(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldValidationMode, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldIntervalSeconds, v))
}

// TimeoutSeconds applies equality check predicate on the "timeout_seconds" field. It's identical to TimeoutSecondsEQ.
func TimeoutSeconds(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// SlowLatencyMs applies equality check predicate on the "slow_latency_ms" field. It's identical to SlowLatencyMsEQ.
func SlowLatencyMs(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldSlowLatencyMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldGroupID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldEnabled, v))
}

// ProbeModelEQ applies the EQ predicate on the "probe_model" field.
func ProbeModelEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldProbeModel, v))
}

// ProbeModelNEQ applies the NEQ predicate on the "probe_model" field.
func ProbeModelNEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldProbeModel, v))
}

// ProbeModelIn applies the In predicate on the "probe_model" field.
func ProbeModelIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldProbeModel, vs...))
}

// ProbeModelNotIn applies the NotIn predicate on the "probe_model" field.
func ProbeModelNotIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldProbeModel, vs...))
}

// ProbeModelGT applies the GT predicate on the "probe_model" field.
func ProbeModelGT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldProbeModel, v))
}

// ProbeModelGTE applies the GTE predicate on the "probe_model" field.
func ProbeModelGTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldProbeModel, v))
}

// ProbeModelLT applies the LT predicate on the "probe_model" field.
func ProbeModelLT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldProbeModel, v))
}

// ProbeModelLTE applies the LTE predicate on the "probe_model" field.
func ProbeModelLTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldProbeModel, v))
}

// ProbeModelContains applies the Contains predicate on the "probe_model" field.
func ProbeModelContains(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContains(FieldProbeModel, v))
}

// ProbeModelHasPrefix applies the HasPrefix predicate on the "probe_model" field.
func ProbeModelHasPrefix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasPrefix(FieldProbeModel, v))
}

// ProbeModelHasSuffix applies the HasSuffix predicate on the "probe_model" field.
func ProbeModelHasSuffix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasSuffix(FieldProbeModel, v))
}

// ProbeModelEqualFold applies the EqualFold predicate on the "probe_model" field.
func ProbeModelEqualFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEqualFold(FieldProbeModel, v))
}

// ProbeModelContainsFold applies the ContainsFold predicate on the "probe_model" field.
func ProbeModelContainsFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContainsFold(FieldProbeModel, v))
}

// ProbePromptEQ applies the EQ predicate on the "probe_prompt" field.
func ProbePromptEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldProbePrompt, v))
}

// ProbePromptNEQ applies the NEQ predicate on the "probe_prompt" field.
func ProbePromptNEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldProbePrompt, v))
}

// ProbePromptIn applies the In predicate on the "probe_prompt" field.
func ProbePromptIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldProbePrompt, vs...))
}

// ProbePromptNotIn applies the NotIn predicate on the "probe_prompt" field.
func ProbePromptNotIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldProbePrompt, vs...))
}

// ProbePromptGT applies the GT predicate on the "probe_prompt" field.
func ProbePromptGT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldProbePrompt, v))
}

// ProbePromptGTE applies the GTE predicate on the "probe_prompt" field.
func ProbePromptGTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldProbePrompt, v))
}

// ProbePromptLT applies the LT predicate on the "probe_prompt" field.
func ProbePromptLT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldProbePrompt, v))
}

// ProbePromptLTE applies the LTE predicate on the "probe_prompt" field.
func ProbePromptLTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldProbePrompt, v))
}

// ProbePromptContains applies the Contains predicate on the "probe_prompt" field.
func ProbePromptContains(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContains(FieldProbePrompt, v))
}

// ProbePromptHasPrefix applies the HasPrefix predicate on the "probe_prompt" field.
func ProbePromptHasPrefix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasPrefix(FieldProbePrompt, v))
}

// ProbePromptHasSuffix applies the HasSuffix predicate on the "probe_prompt" field.
func ProbePromptHasSuffix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasSuffix(FieldProbePrompt, v))
}

// ProbePromptEqualFold applies the EqualFold predicate on the "probe_prompt" field.
func ProbePromptEqualFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEqualFold(FieldProbePrompt, v))
}

// ProbePromptContainsFold applies the ContainsFold predicate on the "probe_prompt" field.
func ProbePromptContainsFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContainsFold(FieldProbePrompt, v))
}

// ValidationModeEQ applies the EQ predicate on the "validation_mode" field.
func ValidationModeEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldValidationMode, v))
}

// ValidationModeNEQ applies the NEQ predicate on the "validation_mode" field.
func ValidationModeNEQ(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldValidationMode, v))
}

// ValidationModeIn applies the In predicate on the "validation_mode" field.
func ValidationModeIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldValidationMode, vs...))
}

// ValidationModeNotIn applies the NotIn predicate on the "validation_mode" field.
func ValidationModeNotIn(vs ...string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldValidationMode, vs...))
}

// ValidationModeGT applies the GT predicate on the "validation_mode" field.
func ValidationModeGT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldValidationMode, v))
}

// ValidationModeGTE applies the GTE predicate on the "validation_mode" field.
func ValidationModeGTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldValidationMode, v))
}

// ValidationModeLT applies the LT predicate on the "validation_mode" field.
func ValidationModeLT(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldValidationMode, v))
}

// ValidationModeLTE applies the LTE predicate on the "validation_mode" field.
func ValidationModeLTE(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldValidationMode, v))
}

// ValidationModeContains applies the Contains predicate on the "validation_mode" field.
func ValidationModeContains(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContains(FieldValidationMode, v))
}

// ValidationModeHasPrefix applies the HasPrefix predicate on the "validation_mode" field.
func ValidationModeHasPrefix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasPrefix(FieldValidationMode, v))
}

// ValidationModeHasSuffix applies the HasSuffix predicate on the "validation_mode" field.
func ValidationModeHasSuffix(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldHasSuffix(FieldValidationMode, v))
}

// ValidationModeEqualFold applies the EqualFold predicate on the "validation_mode" field.
func ValidationModeEqualFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEqualFold(FieldValidationMode, v))
}

// ValidationModeContainsFold applies the ContainsFold predicate on the "validation_mode" field.
func ValidationModeContainsFold(v string) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldContainsFold(FieldValidationMode, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldIntervalSeconds, v))
}

// TimeoutSecondsEQ applies the EQ predicate on the "timeout_seconds" field.
func TimeoutSecondsEQ(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsNEQ applies the NEQ predicate on the "timeout_seconds" field.
func TimeoutSecondsNEQ(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsIn applies the In predicate on the "timeout_seconds" field.
func TimeoutSecondsIn(vs ...int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsNotIn applies the NotIn predicate on the "timeout_seconds" field.
func TimeoutSecondsNotIn(vs ...int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsGT applies the GT predicate on the "timeout_seconds" field.
func TimeoutSecondsGT(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsGTE applies the GTE predicate on the "timeout_seconds" field.
func TimeoutSecondsGTE(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLT applies the LT predicate on the "timeout_seconds" field.
func TimeoutSecondsLT(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLTE applies the LTE predicate on the "timeout_seconds" field.
func TimeoutSecondsLTE(v int) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldTimeoutSeconds, v))
}

// SlowLatencyMsEQ applies the EQ predicate on the "slow_latency_ms" field.
func SlowLatencyMsEQ(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldEQ(FieldSlowLatencyMs, v))
}

// SlowLatencyMsNEQ applies the NEQ predicate on the "slow_latency_ms" field.
func SlowLatencyMsNEQ(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNEQ(FieldSlowLatencyMs, v))
}

// SlowLatencyMsIn applies the In predicate on the "slow_latency_ms" field.
func SlowLatencyMsIn(vs ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldIn(FieldSlowLatencyMs, vs...))
}

// SlowLatencyMsNotIn applies the NotIn predicate on the "slow_latency_ms" field.
func SlowLatencyMsNotIn(vs ...int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldNotIn(FieldSlowLatencyMs, vs...))
}

// SlowLatencyMsGT applies the GT predicate on the "slow_latency_ms" field.
func SlowLatencyMsGT(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGT(FieldSlowLatencyMs, v))
}

// SlowLatencyMsGTE applies the GTE predicate on the "slow_latency_ms" field.
func SlowLatencyMsGTE(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldGTE(FieldSlowLatencyMs, v))
}

// SlowLatencyMsLT applies the LT predicate on the "slow_latency_ms" field.
func SlowLatencyMsLT(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLT(FieldSlowLatencyMs, v))
}

// SlowLatencyMsLTE applies the LTE predicate on the "slow_latency_ms" field.
func SlowLatencyMsLTE(v int64) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.FieldLTE(FieldSlowLatencyMs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupStatusConfig) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupStatusConfig) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupStatusConfig) predicate.GroupStatusConfig {
	return predicate.GroupStatusConfig(sql.NotPredicates(p))
}
